import './editor.css';
import type { ContentPack,WorldObject } from '../shared/data/content';
import { applyContent,exportContent,validateContent } from '../shared/data/content';
import { SLOTS,RARITIES,STAT_NAMES } from '../shared/data/rarities';
import { createItem,seededRandom } from '../shared/domains/item';
import { rollLoot } from '../shared/domains/loot';
import { calculateStats } from '../shared/domains/equipment';
import { CombatFormulaService } from '../shared/domains/combat-formula';
import { WEAPON_PROFILES } from '../shared/data/skills';
import { ModelPreview } from '../client/rendering/preview';
import { drawMap } from '../client/ui/map-canvas';
import { icon,escapeHtml as esc } from '../client/ui/icons';
import { History } from './history';
import { EditorMapView } from './map-view';
import type { ItemInstance,Slot } from '../shared/types';
type Tab='map'|'characters'|'monsters'|'items'|'skills'|'loot'|'effects'|'balance';
type Field={key:string;label:string;type?:string;min?:number;max?:number;step?:number;options?:{id:string;name:string}[]};
export class Editor {
 private content=exportContent();private history=new History<ContentPack>();private tab:Tab='map';private selected='landmark-0';private key='';private dirty=false;private preview?:ModelPreview;private map3d?:EditorMapView;private view3d=false;private canvas?:HTMLCanvasElement;private filter='';private last=performance.now();private tickTime=0;private drawTool='select';private drag?:{id:string;before:ContentPack};private adminPlayers:{id:string;name:string;level:number}[]=[];
 constructor(private host:HTMLElement){
  host.classList.add('editor-app');host.innerHTML=`<header class="editor-header"><a href="/" class="editor-brand"><b>青嵐志</b><span>世界工坊</span></a><div class="editor-project"><i></i>青嵐谷 <span>本地專案</span></div><nav><button id="editor-undo" title="復原 Ctrl+Z">↶ <span>復原</span></button><button id="editor-redo" title="重做 Ctrl+Y">↷ <span>重做</span></button><i></i><button id="editor-draft">儲存草稿</button><button id="editor-validate">驗證</button><button class="primary" id="editor-publish">發布至遊戲</button><a href="/" class="editor-play">▷ 試玩</a></nav></header>
   <div class="editor-workspace"><nav class="editor-rail">${([['map','map','地圖'],['characters','person','人物'],['monsters','fang','異獸'],['items','sword','裝備'],['skills','thunder','技能'],['loot','bag','掉落'],['effects','rune','效果'],['balance','settings','平衡']] as const).map(([id,i,n])=>`<button data-tab="${id}" title="${n}">${icon(i)}<span>${n}</span></button>`).join('')}</nav><aside class="content-browser"><div class="browser-heading"><h2 id="browser-title">場景物件</h2><button id="editor-add" title="新增">＋</button></div><input id="editor-search" placeholder="搜尋內容…"/><div class="browser-tools"><button id="editor-import-glb">匯入 GLB</button><input id="editor-import-glb-file" type="file" accept=".glb,model/gltf-binary,application/octet-stream" hidden/><button id="editor-duplicate">複製</button><button id="editor-delete">刪除</button></div><div id="content-list"></div><div class="browser-bottom"><span id="content-count"></span><button id="editor-export" title="匯出內容 JSON">匯出 ↗</button></div></aside><main class="editor-main"><div class="viewport-toolbar"><div><span id="selection-path"></span><b id="selection-name"></b></div><div id="view-actions"></div></div><div id="editor-viewport"></div><div class="editor-info"><span id="editor-hint"></span><span id="editor-selection-meta"></span></div></main><aside class="inspector"><header><h2>屬性</h2><span>即時預覽</span></header><div id="editor-inspector"></div></aside></div><footer class="editor-status"><span id="editor-notice">世界工坊已就緒</span><div><span id="editor-dirty">已同步</span><span id="data-version">Data v1</span><span>本地 · 伺服器權威</span></div></footer><div id="editor-dialog" hidden></div>`;
  this.bind();void this.load();this.animate();
 }
 private async load(){const response=await fetch('/api/content');const data=await response.json();this.content=data.content;this.key=data.editorKey;this.render();const draft=localStorage.getItem('qinglan-editor-draft');if(draft)this.notice('已發現本地草稿。按「載入草稿」可繼續上次編輯。');}
 private bind(){
  this.host.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab as Tab;this.selected=this.entries()[0]?.id??'';this.filter='';this.host.querySelector<HTMLInputElement>('#editor-search')!.value='';this.render();});
  this.host.querySelector<HTMLInputElement>('#editor-search')!.oninput=e=>{this.filter=(e.target as HTMLInputElement).value;this.renderList();};
  this.on('editor-undo',()=>{this.content=this.history.undo(this.content);this.dirty=true;this.render();});this.on('editor-redo',()=>{this.content=this.history.redo(this.content);this.dirty=true;this.render();});
  this.on('editor-add',()=>this.add());this.on('editor-import-glb',()=>this.host.querySelector<HTMLInputElement>('#editor-import-glb-file')!.click());this.host.querySelector<HTMLInputElement>('#editor-import-glb-file')!.onchange=e=>{const input=e.currentTarget as HTMLInputElement,file=input.files?.[0];input.value='';if(file)void this.importEquipmentGlb(file);};this.on('editor-duplicate',()=>this.duplicate());this.on('editor-delete',()=>this.remove());this.on('editor-draft',()=>{localStorage.setItem('qinglan-editor-draft',JSON.stringify(this.content));this.notice('草稿已儲存在此瀏覽器；遊戲內容尚未改變。');});
  this.on('editor-validate',()=>this.validate());this.on('editor-publish',()=>void this.publish());this.on('editor-export',()=>{const blob=new Blob([JSON.stringify(this.content,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`qinglan-content-v${this.content.dataVersion}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
  window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['z','y','s'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='s')this.host.querySelector<HTMLButtonElement>('#editor-draft')!.click();else this.host.querySelector<HTMLButtonElement>(e.key.toLowerCase()==='y'||e.shiftKey?'#editor-redo':'#editor-undo')!.click();}});
  window.addEventListener('beforeunload',e=>{if(this.dirty){e.preventDefault();e.returnValue='';}});
 }
 private on(id:string,action:()=>void){this.host.querySelector<HTMLButtonElement>('#'+id)!.onclick=action;}
 private notice(text:string){this.host.querySelector('#editor-notice')!.textContent=text;}
 private mutate(fn:()=>void,render=true){this.history.record(this.content);fn();this.dirty=true;if(render)this.render();else this.renderStatus();}
 private entries():{id:string;name:string;description:string;icon:string;color?:string}[]{const c=this.content;
  if(this.tab==='map')return [...c.objects.map(o=>({id:o.id,name:o.kind==='monster'?c.monsters[o.monsterId!]?.name??o.id:({rock:'山石',house:'古居',pavilion:'亭閣',lake:'湖泊',bamboo:'竹叢',tree:'古松',lantern:'石燈'}[o.kind]??o.kind),description:`${o.id} · ${o.x.toFixed(0)}, ${o.z.toFixed(0)}`,icon:o.kind==='monster'?'fang':o.kind==='lake'?'disc':'map'})),...c.spawnZones.map(z=>({id:z.id,name:'生成區 · '+(c.monsters[z.monsterId]?.name??''),description:`${z.maxCount} 隻 · 半徑 ${z.radius}`,icon:'compass'})),...c.regions.map(r=>({id:'region:'+r.id,name:r.name,description:r.level,icon:'map'}))];
  if(this.tab==='items')return Object.values(c.items).map(i=>({id:i.id,name:i.name,description:`${i.slot?SLOTS[i.slot]:'靈材'} · ${RARITIES[i.rarity].name}`,icon:i.icon,color:RARITIES[i.rarity].color}));
  if(this.tab==='monsters')return Object.values(c.monsters).map(m=>({id:m.id,name:m.name,description:`Lv. ${m.level} · ${m.aiProfile}`,icon:'fang'}));
  if(this.tab==='characters')return c.characters.map(ch=>({id:ch.id,name:ch.name,description:ch.id,icon:'person'}));
  if(this.tab==='skills')return Object.values(c.skills).map(s=>({id:s.id,name:s.name,description:`冷卻 ${s.cooldown}s · ${s.cost} 靈力`,icon:'thunder'}));
  if(this.tab==='effects')return Object.values(c.effects).map(e=>({id:e.id,name:e.name,description:`${e.kind} · ${e.duration}s`,icon:'rune',color:e.color}));
  if(this.tab==='loot')return Object.values(c.lootTables).map(t=>({id:t.id,name:c.monsters[t.id]?.name??t.id,description:`${t.entries.length} 個掉落 · ${t.rolls} 次擲骰`,icon:'bag'}));
  return [{id:'formulas',name:'戰鬥公式',description:'集中式 CombatFormulaService',icon:'thunder'},{id:'loot-simulation',name:'掉寶模擬',description:'100,000 次樣本分布',icon:'bag'},{id:'developer',name:'開發者工具',description:'本地開發伺服器限定',icon:'settings'}];
 }
 private render(){this.preview?.dispose();this.preview=undefined;this.map3d?.dispose();this.map3d=undefined;this.canvas=undefined;this.host.querySelectorAll<HTMLElement>('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===this.tab));this.renderList();this.renderViewport();this.renderInspector();this.renderStatus();}
 private renderList(){const importButton=this.host.querySelector<HTMLButtonElement>('#editor-import-glb');if(importButton)importButton.hidden=this.tab!=='items';const labels:Record<Tab,string>={map:'場景物件',characters:'人物原型',monsters:'異獸原型',items:'裝備與物品',skills:'戰鬥技能',loot:'掉落資料表',effects:'狀態效果',balance:'平衡工具'};this.host.querySelector('#browser-title')!.textContent=labels[this.tab];const entries=this.entries().filter(e=>(e.name+e.description).toLowerCase().includes(this.filter.toLowerCase()));this.host.querySelector('#content-list')!.innerHTML=entries.map(e=>`<button data-content="${esc(e.id)}" class="${e.id===this.selected?'active':''}"><i style="color:${e.color??'#b7c4b2'}">${icon(e.icon)}</i><div><span>${esc(e.name)}</span><small>${esc(e.description)}</small></div></button>`).join('');this.host.querySelectorAll<HTMLButtonElement>('[data-content]').forEach(b=>b.onclick=()=>{this.selected=b.dataset.content!;this.render();});this.host.querySelector('#content-count')!.textContent=`${entries.length} 個項目`;}
 private renderStatus(){this.host.querySelector('#editor-dirty')!.textContent=this.dirty?'● 有未發布的更動':'● 與遊戲同步';this.host.querySelector('#data-version')!.textContent=`Data v${this.content.dataVersion}`;(this.host.querySelector('#editor-undo') as HTMLButtonElement).disabled=!this.history.canUndo;(this.host.querySelector('#editor-redo') as HTMLButtonElement).disabled=!this.history.canRedo;}
 private renderViewport(){const viewport=this.host.querySelector<HTMLElement>('#editor-viewport')!,actions=this.host.querySelector<HTMLElement>('#view-actions')!,entry=this.entries().find(e=>e.id===this.selected);this.host.querySelector('#selection-name')!.textContent=entry?.name??'選取內容';this.host.querySelector('#selection-path')!.textContent=`青嵐谷 / ${this.tab}`;this.host.querySelector('#editor-selection-meta')!.textContent=this.selected;actions.innerHTML='';
  if(this.tab==='map'){
   actions.innerHTML=`<select id="map-tool"><option value="select">選取 / 拖曳</option><option value="rock">放置山石</option><option value="house">放置古居</option><option value="pavilion">放置亭閣</option><option value="lantern">放置石燈</option><option value="monster">放置異獸</option><option value="zone">繪製生成區</option></select><button id="map-view-toggle">${this.view3d?'俯視編輯':'3D 場景'}</button>`;actions.querySelector<HTMLSelectElement>('#map-tool')!.value=this.drawTool;actions.querySelector<HTMLSelectElement>('#map-tool')!.onchange=e=>{this.drawTool=(e.target as HTMLSelectElement).value;if(this.view3d){this.view3d=false;this.render();}};this.on('map-view-toggle',()=>{this.view3d=!this.view3d;this.render();});
   if(this.view3d){viewport.innerHTML='<div class="editor-scene"></div>';this.map3d=new EditorMapView(viewport.querySelector<HTMLElement>('.editor-scene')!,this.content);this.host.querySelector('#editor-hint')!.textContent='拖曳旋轉 · 右鍵平移 · 滾輪縮放 · 返回俯視模式配置物件';}
   else {viewport.innerHTML='<div class="map-editor-stage"><canvas id="map-editor-canvas" width="900" height="800"></canvas><div class="map-overlay-label"><span>青 嵐 谷</span><small>WORLD COMPOSITION</small></div></div>';this.canvas=viewport.querySelector('canvas')!;this.drawMap();this.bindMap();this.host.querySelector('#editor-hint')!.textContent='點選物件 · 拖曳調整位置 · 選擇工具後點地圖新增 · 生成區可拖曳繪製半徑';}return;
  }
  if(this.tab==='loot'){viewport.innerHTML='<div class="editor-table-stage" id="loot-editor"></div>';this.renderLoot();this.host.querySelector('#editor-hint')!.textContent='權重決定每次擲骰的相對機率；保證掉落獨立計算。';return;}
  if(this.tab==='balance'){this.renderBalance(viewport);return;}
  viewport.innerHTML=`<div class="model-editor-stage"><div id="editor-model"></div><div class="model-platform"></div><div class="model-label"><span>${esc(entry?.name??'')}</span><small>${esc(entry?.description??'')}</small></div><div class="model-view-tag">PERSPECTIVE <span>·</span> PBR MATERIAL</div></div>`;
  applyContent(this.content);this.preview=new ModelPreview(viewport.querySelector<HTMLElement>('#editor-model')!);
  if(this.tab==='monsters'){const def=this.content.monsters[this.selected];if(def)this.preview.setMonster(def);}
  else if(this.tab==='characters'){const def=this.content.characters.find(c=>c.id===this.selected);if(def)this.preview.resetCharacter(def);}
  else if(this.tab==='items'){
   const equipment:Partial<Record<Slot,ItemInstance>>={};for(const id of this.content.characters[0].outfit){const i=createItem(id);i.identified=true;equipment[this.content.items[id].slot!]=i;}const item=this.content.items[this.selected];if(item?.slot){const instance=createItem(item.id);instance.identified=true;equipment[item.slot]=instance;}this.preview.setCharacter(equipment);
  }else this.preview.resetCharacter();
  this.host.querySelector('#editor-hint')!.textContent='拖曳旋轉 3D 模型 · 滾輪縮放 · 修改右側屬性以更新預覽';
 }
 private drawMap(){if(!this.canvas)return;applyContent(this.content);drawMap(this.canvas,undefined,false);const ctx=this.canvas.getContext('2d')!,w=this.canvas.width,h=this.canvas.height;
  for(const z of this.content.spawnZones){const x=(z.x+120)/240*w,y=(z.z+120)/240*h;ctx.fillStyle=z.id===this.selected?'#c4d7a144':'#b7afdf22';ctx.strokeStyle=z.id===this.selected?'#e0d29d':'#b7afdf';ctx.beginPath();ctx.ellipse(x,y,z.radius/240*w,z.radius/240*h,0,0,Math.PI*2);ctx.fill();ctx.setLineDash([5,5]);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#e1dfca';ctx.font='12px sans-serif';ctx.fillText(`${this.content.monsters[z.monsterId]?.name} ×${z.maxCount}`,x+8,y-9);}
  for(const o of this.content.objects){const x=(o.x+120)/240*w,y=(o.z+120)/240*h;ctx.fillStyle=o.kind==='monster'?'#c99085':o.kind==='lake'?'#8dc2c5':'#c2c5a1';ctx.strokeStyle='#14292c';ctx.lineWidth=2;ctx.beginPath();if(o.kind==='monster')ctx.arc(x,y,5,0,6.28);else ctx.rect(x-4,y-4,8,8);ctx.fill();ctx.stroke();if(o.id===this.selected){ctx.strokeStyle='#ffdb93';ctx.lineWidth=2;ctx.strokeRect(x-11,y-11,22,22);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+24,y);ctx.moveTo(x,y);ctx.lineTo(x,y-24);ctx.stroke();}}
 }
 private bindMap(){const canvas=this.canvas!;const point=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();return {x:Math.max(-105,Math.min(105,(e.clientX-r.left)/r.width*240-120)),z:Math.max(-105,Math.min(105,(e.clientY-r.top)/r.height*240-120))};};
  canvas.onpointerdown=e=>{const p=point(e);canvas.setPointerCapture(e.pointerId);
   if(this.drawTool!=='select'){const id=this.uid(this.drawTool);if(this.drawTool==='zone'){const before=structuredClone(this.content);this.content.spawnZones.push({id,monsterId:'wolf',...p,radius:4,maxCount:6,respawn:35,patrolRadius:6,eliteChance:.03,activationDistance:85});this.selected=id;this.drag={id,before};this.dirty=true;this.drawMap();return;}
    this.mutate(()=>{this.content.objects.push({id,kind:this.drawTool as WorldObject['kind'],...p,scale:['rock','house','pavilion'].includes(this.drawTool)?3:1,rotation:0,...this.drawTool==='monster'?{monsterId:'wolf'}:{}});this.selected=id;});return;
   }
   const object=[...this.content.objects,...this.content.spawnZones].map(o=>({o,d:Math.hypot(o.x-p.x,o.z-p.z)})).sort((a,b)=>a.d-b.d)[0];if(object&&object.d<6){this.selected=object.o.id;this.drag={id:object.o.id,before:structuredClone(this.content)};this.drawMap();this.renderList();this.renderInspector();}
  };
  canvas.onpointermove=e=>{if(!this.drag)return;const p=point(e),zone=this.content.spawnZones.find(z=>z.id===this.drag!.id),object=zone??this.content.objects.find(o=>o.id===this.drag!.id);if(!object)return;if(zone&&this.drawTool==='zone')zone.radius=Math.max(1,Math.min(35,Math.hypot(p.x-zone.x,p.z-zone.z)));else {object.x=+p.x.toFixed(1);object.z=+p.z.toFixed(1);}this.drawMap();};
  canvas.onpointerup=()=>{if(this.drag){this.history.record(this.drag.before);this.drag=undefined;this.dirty=true;this.render();}};
 }
 private selectedObject():Record<string,any>|undefined{const c=this.content;if(this.tab==='map')return this.selected.startsWith('region:')?c.regions.find(r=>r.id===this.selected.slice(7)):c.objects.find(o=>o.id===this.selected)??c.spawnZones.find(z=>z.id===this.selected);if(this.tab==='characters')return c.characters.find(c=>c.id===this.selected);if(this.tab==='monsters')return c.monsters[this.selected];if(this.tab==='items')return c.items[this.selected];if(this.tab==='skills')return c.skills[this.selected];if(this.tab==='effects')return c.effects[this.selected];if(this.tab==='loot')return c.lootTables[this.selected];if(this.selected==='formulas')return c.balance;}
 private fieldHtml(field:Field,obj:Record<string,any>,prefix=''){const value=field.key.split('.').reduce((o,k)=>o?.[k],obj);const attrs=`data-field="${prefix+field.key}"`;return `<label class="inspector-field"><span>${field.label}</span>${field.options?`<select ${attrs}>${field.options.map(o=>`<option value="${esc(o.id)}" ${o.id===String(value??'')?'selected':''}>${esc(o.name)}</option>`).join('')}</select>`:field.type==='textarea'?`<textarea ${attrs} rows="3">${esc(value)}</textarea>`:`<input ${attrs} type="${field.type??'text'}" value="${esc(value??0)}" ${field.min!==undefined?`min="${field.min}"`:''} ${field.max!==undefined?`max="${field.max}"`:''} ${field.step!==undefined?`step="${field.step}"`:''}/>`}</label>`;}
 private renderInspector(){const el=this.host.querySelector<HTMLElement>('#editor-inspector')!,obj=this.selectedObject();if(!obj){el.innerHTML='<p class="inspector-empty">選取項目以檢視與修改屬性。</p>';return;}
  const number=(key:string,label:string,min=0,max=10000,step=.1):Field=>({key,label,type:'number',min,max,step}),options=(r:Record<string,{name:string}>)=>Object.entries(r).map(([id,v])=>({id,name:v.name}));let fields:Field[]=[];
  if(this.tab==='items')fields=[{key:'name',label:'物品名稱'},{key:'rarity',label:'稀有度',options:Object.entries(RARITIES).map(([id,r])=>({id,name:r.name}))},number('requiredLevel','需求等級',1,999,1),number('itemLevel','物品等級',1,999,1),...(['attack','defense','hp','crit','haste','lightning','penetration'] as const).map(k=>number('baseStats.'+k,STAT_NAMES[k],0,1e5,1)),number('sellPrice','基準售價',0,1e9,1),{key:'description',label:'物品描述',type:'textarea'}];
  if(this.tab==='monsters')fields=[{key:'name',label:'異獸名稱'},number('level','等級',1,999,1),number('hp','氣血',1,1e7,1),number('attack','攻擊',0,1e5,1),number('defense','防禦',0,1e5,1),number('speed','移動速度',.1,15),number('aggroRange','警戒距離',0,30),number('attackRange','攻擊距離',1,25),number('scale','模型比例',.2,8),{key:'color',label:'皮毛色彩',type:'color'},{key:'model',label:'模型骨架',options:['wolf','snake','turtle','fox','zheng','gudiao','golden-queen','kui'].map(id=>({id,name:id}))},{key:'aiProfile',label:'AI 行為',options:['pack','ambush','territorial','passive','boss','ranged'].map(id=>({id,name:id}))},{key:'spawnArea',label:'棲息地',options:this.content.regions},{key:'lootTable',label:'掉落表',options:Object.keys(this.content.lootTables).map(id=>({id,name:id}))},number('respawn','重生秒數',5,3600,1),{key:'description',label:'生態描述',type:'textarea'}];
  if(this.tab==='characters')fields=[{key:'name',label:'人物名稱'},number('height','身高比例',.75,1.3,.01),number('build','體型比例',.65,1.5,.01),{key:'skin',label:'膚色',type:'color'},{key:'hair',label:'髮色',type:'color'}];
  if(this.tab==='map')fields=this.selected.startsWith('region:')?[{key:'name',label:'區域名稱'},{key:'level',label:'建議等級'},number('x','中心 X',-105,105,1),number('z','中心 Z',-105,105,1),number('radius','區域半徑',1,50,1),{key:'color',label:'地圖色彩',type:'color'},{key:'description',label:'區域描述',type:'textarea'}]:obj.maxCount!==undefined?[{key:'monsterId',label:'生成異獸',options:options(this.content.monsters)},number('x','中心 X',-105,105),number('z','中心 Z',-105,105),number('radius','半徑',1,35),number('maxCount','最大數量',1,30,1),number('respawn','重生秒數',5,3600,1),number('patrolRadius','巡邏半徑',1,30),number('eliteChance','精英機率',0,1,.01),number('activationDistance','啟用距離',20,200,1)]:[number('x','位置 X',-105,105),number('z','位置 Z',-105,105),number('rotation','旋轉（弧度）',-100,100,.1),number('scale','比例 / 碰撞半徑',.1,20,.1),...(obj.kind==='monster'?[{key:'monsterId',label:'異獸原型',options:options(this.content.monsters)}]:[])];
  if(this.tab==='skills')fields=[{key:'name',label:'技能名稱'},number('cooldown','冷卻秒數',.1,120),number('cost','靈力消耗',0,100,1),number('range','施法距離',0,30),number('radius','範圍半徑',0,15),number('windup','前搖秒數',0,5,.05),number('hitFrame','命中幀（秒）',0,5,.05),number('recovery','後搖秒數',.05,5,.05),number('multiplier','傷害倍率',0,20,.1),{key:'animationProfile',label:'動畫 Profile'},{key:'vfx',label:'視覺特效'}];
  if(this.tab==='effects')fields=[{key:'name',label:'狀態名稱'},number('duration','持續秒數',.1,120),number('interval','Tick 間隔',0,30),number('power','每跳強度',0,1000),number('maxStacks','疊加上限',1,20,1),number('moveScale','移動倍率',0,2,.05),{key:'color',label:'效果色彩',type:'color'},...(['attack','defense','lightningResist'] as const).map(k=>number('stats.'+k,STAT_NAMES[k],-100,1000,1))];
  if(this.tab==='loot')fields=[number('rolls','每次討伐擲骰次數',0,12,1),number('chance','每骰掉落機率',0,1,.01)];
  if(this.tab==='balance'&&this.selected==='formulas')fields=Object.keys(this.content.balance).map(k=>number(k,({armorFactor:'護甲係數',minimumHit:'最低命中%',maximumHit:'最高命中%',variance:'隨機浮動',attributeScale:'力道係數',resistanceCap:'抗性上限%'} as Record<string,string>)[k]??k,0,k==='variance'?1:100,.01));
  el.innerHTML=`<div class="inspector-id"><span>識別碼</span><code>${esc(obj.id??'balance')}</code></div><h3>基本屬性</h3>${fields.map(f=>this.fieldHtml(f,obj)).join('')}`;
  if(this.tab==='items'&&obj.appearanceId){const a=this.content.appearances[obj.appearanceId],autoModule=typeof obj.mesh==='string'&&obj.mesh.startsWith('/assets/equipment/modules/');el.innerHTML+=`<h3>3D 外觀</h3>${[{key:'shape',label:'Mesh 輪廓',options:[...new Set(Object.values(this.content.appearances).filter(x=>x.slot===a.slot).map(x=>x.shape))].map(id=>({id,name:id}))},{key:'color',label:'主材質色彩',type:'color'},{key:'trim',label:'飾邊色彩',type:'color'},number('length','長度',.02,5,.02),number('width','寬度',.01,3,.01),number('ornaments','裝飾數量',0,12,1),{key:'vfx',label:'器靈特效',options:[{id:'',name:'無'},...['lightning','flame','frost','runes','aura'].map(id=>({id,name:id}))]}].map(f=>this.fieldHtml(f as Field,a,'appearance.')).join('')}<p class="inspector-note">${autoModule?'✓ HF9 一鍵匯入裝備 · 自動 Fit 管理<br>':''}裝備槽位 ${esc(SLOTS[a.slot])}<br>外觀綁定 ${esc(a.attachBone)}<br>身體遮罩 ${a.hideBody.join(', ')||'無'}<br>動畫 ${a.animationProfile??'護甲共用骨架'}</p>`;}
  if(this.tab==='characters')el.innerHTML+=`<h3>預設配裝</h3>${(Object.keys(SLOTS) as Slot[]).filter(slot=>['head','chest','mainhand','legs','feet','shoulders','cape','artifact'].includes(slot)).map(slot=>`<label class="inspector-field"><span>${SLOTS[slot]}</span><select data-outfit="${slot}"><option value="">無</option>${Object.values(this.content.items).filter(i=>i.slot===slot).map(i=>`<option value="${i.id}" ${obj.outfit.includes(i.id)?'selected':''}>${esc(i.name)}</option>`).join('')}</select></label>`).join('')}`;
  if(this.tab==='skills')el.innerHTML+=`<h3>套用狀態</h3>${Object.values(this.content.effects).map(e=>`<label class="effect-check"><input type="checkbox" data-skill-effect="${e.id}" ${obj.effects.includes(e.id)?'checked':''}/> ${e.name}</label>`).join('')}`;
  if(this.tab==='map')el.innerHTML+='<button id="editor-add-region" class="wide-button">＋ 新增探索區域</button>';
  el.innerHTML+='<button id="editor-load-draft" class="wide-button">載入本地草稿</button>';
  el.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[data-field]').forEach(input=>input.onchange=()=>{this.mutate(()=>{let path=input.dataset.field!.split('.'),target=obj;if(path[0]==='appearance'){target=this.content.appearances[obj.appearanceId];path.shift();}for(const p of path.slice(0,-1))target=target[p]??=( {} );target[path.at(-1)!]=input instanceof HTMLInputElement&&input.type==='number'?Number(input.value):input.value;});});
  el.querySelectorAll<HTMLSelectElement>('[data-outfit]').forEach(input=>input.onchange=()=>this.mutate(()=>{obj.outfit=obj.outfit.filter((id:string)=>this.content.items[id]?.slot!==input.dataset.outfit);if(input.value)obj.outfit.push(input.value);}));
  el.querySelectorAll<HTMLInputElement>('[data-skill-effect]').forEach(input=>input.onchange=()=>this.mutate(()=>{obj.effects=[...el.querySelectorAll<HTMLInputElement>('[data-skill-effect]:checked')].map(i=>i.dataset.skillEffect);}));
  el.querySelector<HTMLButtonElement>('#editor-add-region')?.addEventListener('click',()=>this.mutate(()=>{const id=this.uid('region');this.content.regions.push({id,name:'未名山境',level:'建議 Lv. 1–10',x:0,z:0,radius:20,color:'#9aaa91',description:'一處尚待探索的新地區。'});this.selected='region:'+id;}));
  this.on('editor-load-draft',()=>{const saved=localStorage.getItem('qinglan-editor-draft');if(!saved){this.notice('尚無已儲存的草稿。');return;}try{this.mutate(()=>this.content=JSON.parse(saved));this.notice('已載入草稿，尚未發布。');}catch{this.notice('草稿格式無法讀取。');}});
 }

 private async importEquipmentGlb(file:File){
  if(!/\.glb$/i.test(file.name)){this.notice('請選擇 GLB 2.0 裝備檔案。');return;}if(file.size>100*1024*1024){this.notice('GLB 超過 100 MB 匯入上限。');return;}
  this.notice(`正在分析並匯入 ${file.name}…`);
  const button=this.host.querySelector<HTMLButtonElement>('#editor-import-glb');if(button)button.disabled=true;
  try{
   if(this.dirty){if(!this.validate())return;const save=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json','x-editor-key':this.key},body:JSON.stringify(this.content)}),saved=await save.json();if(!save.ok){this.notice('匯入前自動儲存失敗：'+(saved.error??`HTTP ${save.status}`));return;}this.dirty=false;localStorage.removeItem('qinglan-editor-draft');}
   const response=await fetch('/api/editor/import-equipment',{method:'POST',headers:{'Content-Type':'model/gltf-binary','x-editor-key':this.key,'x-file-name':encodeURIComponent(file.name)},body:file}),result=await response.json();
   if(!response.ok){this.notice('GLB 匯入失敗：'+(result.error??`HTTP ${response.status}`));return;}
   this.content=result.content;this.tab='items';this.selected=result.itemId;this.filter='';this.dirty=false;localStorage.removeItem('qinglan-editor-draft');this.host.querySelector<HTMLInputElement>('#editor-search')!.value='';this.render();
   const slotName=SLOTS[result.fit.slot as Slot]??result.fit.slot,strategy=result.fit.strategy==='skinned-rebind'?'既有骨架重綁':result.fit.strategy==='rigid-auto-rig'?'自動骨架綁定':'Rigid 掛點',confidence=Math.round(Number(result.fit.confidence??0)*100);this.notice(`匯入完成：${slotName} · ${strategy} · 自動判定信心 ${confidence}% · 已套用 HF9 規範`);
  }catch(error){this.notice(`GLB 匯入失敗：${error instanceof Error?error.message:'無法連線至本機編輯器伺服器。'}`);}finally{if(button)button.disabled=false;}
 }
 private uid(prefix:string){return prefix+'-'+Date.now().toString(36).slice(-6);}
 private add(){if(this.tab==='map'){this.drawTool='monster';this.view3d=false;this.render();this.notice('點選地圖以放置新異獸；工具列亦可選擇山石、建築或生成區。');return;}this.duplicate(true);}
 private duplicate(newName=false){const obj=this.selectedObject();if(!obj||this.tab==='balance'){this.notice('請先選取可複製的項目。');return;}this.mutate(()=>{const clone=structuredClone(obj),id=this.uid(this.tab==='items'?'item':this.tab);clone.id=id;if(clone.name)clone.name=(newName?'新建 · ':'副本 · ')+clone.name;
  if(this.tab==='items'){const a=structuredClone(this.content.appearances[clone.appearanceId]);if(a){a.id='equipment_'+id;this.content.appearances[a.id]=a;clone.appearanceId=a.id;}this.content.items[id]=clone as ContentPack['items'][string];}
  else if(this.tab==='map'){if(this.selected.startsWith('region:')){this.content.regions.push(clone as typeof this.content.regions[number]);this.selected='region:'+id;return;}clone.x=Math.min(105,clone.x+3);clone.z=Math.min(105,clone.z+3);if(clone.maxCount!==undefined)this.content.spawnZones.push(clone as typeof this.content.spawnZones[number]);else this.content.objects.push(clone as WorldObject);}
  else if(this.tab==='characters')this.content.characters.push(clone as typeof this.content.characters[number]);else (this.content[this.tab==='loot'?'lootTables':this.tab] as Record<string,unknown>)[id]=clone;
  this.selected=id;
 });}
 private remove(){const id=this.selected,c=this.content,references:string[]=[];
  if(this.tab==='items'){for(const t of Object.values(c.lootTables))if([...t.entries,...t.guaranteed??[]].some(e=>e.itemId===id))references.push('掉落表 '+t.id);for(const ch of c.characters)if(ch.outfit.includes(id))references.push('人物 '+ch.name);}
  if(this.tab==='monsters'){if(c.objects.some(o=>o.monsterId===id))references.push('地圖生成點');if(c.spawnZones.some(z=>z.monsterId===id))references.push('生成區域');}
  if(this.tab==='loot')for(const m of Object.values(c.monsters))if(m.lootTable===id)references.push('異獸 '+m.name);
  if(this.tab==='effects')for(const s of Object.values(c.skills))if(s.effects.includes(id))references.push('技能 '+s.name);
  if(this.tab==='map'&&id.startsWith('region:'))for(const m of Object.values(c.monsters))if(m.spawnArea===id.slice(7))references.push('異獸 '+m.name);
  if(references.length){this.notice(`無法刪除：仍被 ${references.join('、')} 引用。請先調整引用。`);return;}
  if(this.tab==='characters'&&c.characters.length===1){this.notice('至少保留一個人物原型。');return;}
  if(this.tab==='balance')return;
  this.mutate(()=>{if(this.tab==='map'){c.objects=c.objects.filter(o=>o.id!==id);c.spawnZones=c.spawnZones.filter(z=>z.id!==id);if(id.startsWith('region:'))c.regions=c.regions.filter(r=>r.id!==id.slice(7));}else if(this.tab==='characters')c.characters=c.characters.filter(ch=>ch.id!==id);else delete (c[this.tab==='loot'?'lootTables':this.tab] as Record<string,unknown>)[id];this.selected=this.entries()[0]?.id??'';});this.notice('已從草稿刪除，可按復原還原。');
 }
 private validate(){try{validateContent(this.content);this.notice(`驗證通過 · ${Object.keys(this.content.items).length} 個物品、${Object.keys(this.content.monsters).length} 種異獸、${this.content.objects.length} 個場景物件。`);return true;}catch(e){this.notice('驗證失敗：'+(e as Error).message);return false;}}
 private async publish(){if(!this.validate())return;const response=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json','x-editor-key':this.key},body:JSON.stringify(this.content)});const result=await response.json();if(!response.ok){this.notice('發布失敗：'+result.error);return;}this.content.dataVersion=result.dataVersion??this.content.dataVersion+1;this.dirty=false;localStorage.removeItem('qinglan-editor-draft');this.renderStatus();this.notice(`已發布 Data v${this.content.dataVersion}。重新進入遊戲，即可體驗新內容。`);}
 private renderLoot(){const el=this.host.querySelector<HTMLElement>('#loot-editor')!,table=this.content.lootTables[this.selected];if(!table){el.innerHTML='選取一張掉落表';return;}const total=table.entries.reduce((s,e)=>s+e.weight,0);el.innerHTML=`<div class="table-intro"><h2>${esc(this.content.monsters[this.selected]?.name??table.id)} · 掉落配置</h2><p>每次討伐擲骰 ${table.rolls} 次，每骰 ${Math.round(table.chance*100)}% 機率產出物品。</p></div><table class="loot-table"><thead><tr><th>物品</th><th>權重</th><th>相對機率</th><th>最少</th><th>最多</th><th></th></tr></thead><tbody>${table.entries.map((e,i)=>`<tr><td style="color:${RARITIES[this.content.items[e.itemId].rarity].color}">${icon(this.content.items[e.itemId].icon)}${esc(this.content.items[e.itemId].name)}</td><td><input type="number" data-loot-index="${i}" data-loot-key="weight" min=".01" step=".1" value="${e.weight}"/></td><td><span class="probability-bar"><i style="width:${e.weight/total*100}%"></i></span>${(e.weight/total*100).toFixed(2)}%</td><td><input type="number" data-loot-index="${i}" data-loot-key="minQuantity" min="1" value="${e.minQuantity}"/></td><td><input type="number" data-loot-index="${i}" data-loot-key="maxQuantity" min="1" value="${e.maxQuantity}"/></td><td><button data-remove-loot="${i}">×</button></td></tr>`).join('')}</tbody></table><div class="loot-add"><select id="loot-add-item">${Object.values(this.content.items).map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('')}</select><button id="loot-add-submit">＋ 加入掉落</button></div><div class="guaranteed-loot"><h3>條件保證掉落</h3>${(table.guaranteed??[]).map(e=>`<p>${this.content.items[e.itemId].name} · ${e.conditions==='firstKill'?'首次討伐':'每次討伐'}</p>`).join('')||'<p>無保證項目</p>'}</div>`;
  el.querySelectorAll<HTMLInputElement>('[data-loot-index]').forEach(input=>input.onchange=()=>this.mutate(()=>{(table.entries[Number(input.dataset.lootIndex)] as unknown as Record<string,number>)[input.dataset.lootKey!]=Number(input.value);}));el.querySelectorAll<HTMLButtonElement>('[data-remove-loot]').forEach(b=>b.onclick=()=>this.mutate(()=>table.entries.splice(Number(b.dataset.removeLoot),1)));this.on('loot-add-submit',()=>this.mutate(()=>table.entries.push({itemId:el.querySelector<HTMLSelectElement>('#loot-add-item')!.value,weight:1,minQuantity:1,maxQuantity:1})));
 }
 private renderBalance(viewport:HTMLElement){
  if(this.selected==='formulas'){viewport.innerHTML=`<div class="balance-stage"><small>COMBAT FORMULA SERVICE</small><h2>讓每一劍，都有依據</h2><p>命中判定 → 穿透與護甲 → 元素抗性 → 浮動擲值 → 暴擊倍率</p><div class="formula-visual"><span>力道 / 裝備攻擊</span><b>×</b><span>技能倍率</span><b>→</b><span>防禦與抗性</span><b>→</b><span>最終傷害</span></div><h3>實戰 DPS 估算</h3><select id="dps-weapon">${Object.values(this.content.items).filter(i=>i.slot==='mainhand').map(i=>`<option value="${i.id}">${i.name}</option>`).join('')}</select><button id="simulate-dps" class="primary">模擬 10,000 次攻擊</button><div id="balance-result"></div></div>`;this.on('simulate-dps',()=>{applyContent(this.content);const id=viewport.querySelector<HTMLSelectElement>('#dps-weapon')!.value,item=createItem(id,seededRandom(71));item.identified=true;const stats=calculateStats({level:10,equipment:{mainhand:item}}),defender=CombatFormulaService.monsterStats(this.content.monsters.kui),rng=seededRandom(773);let total=0,miss=0,crit=0;for(let n=0;n<10000;n++){const r=CombatFormulaService.resolve(stats,defender,1,rng);total+=r.value;miss+=r.missed?1:0;crit+=r.critical?1:0;}const profile=WEAPON_PROFILES[this.content.appearances[this.content.items[id].appearanceId!].animationProfile??'sword'];viewport.querySelector('#balance-result')!.innerHTML=`<div class="balance-metrics"><div><b>${(total/10000/(profile.windup+profile.recovery)).toFixed(1)}</b><span>估算 DPS</span></div><div><b>${(total/10000).toFixed(1)}</b><span>平均單擊傷害</span></div><div><b>${(miss/100).toFixed(1)}%</b><span>閃避</span></div><div><b>${(crit/100).toFixed(1)}%</b><span>暴擊</span></div></div><p>Lv.10 行者對雷澤夔牛；固定種子、無技能循環、無走位時間。實戰 DPS 需另行量測。</p>`;});}
  else if(this.selected==='loot-simulation'){
   viewport.innerHTML=`<div class="balance-stage"><small>LOOT DISTRIBUTION</small><h2>十萬次掉寶，檢查期待值</h2><p>使用與遊戲相同的 Loot Domain，統計普通討伐，不計首次保證掉落。</p><select id="simulate-table">${Object.keys(this.content.lootTables).map(id=>`<option value="${id}">${this.content.monsters[id]?.name??id}</option>`).join('')}</select><button class="primary" id="simulate-loot">模擬 100,000 次</button><div id="balance-result"></div></div>`;
   this.on('simulate-loot',()=>{applyContent(this.content);const id=viewport.querySelector<HTMLSelectElement>('#simulate-table')!.value,rng=seededRandom(5321),counts:Record<string,number>={};const start=performance.now();for(let n=0;n<100000;n++)for(const item of rollLoot(id,{firstKill:false,boss:id==='kui'},rng))counts[item.baseId]=(counts[item.baseId]??0)+item.quantity;const max=Math.max(...Object.values(counts));viewport.querySelector('#balance-result')!.innerHTML=`<p>100,000 次討伐 · ${(performance.now()-start).toFixed(0)} ms</p>${Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([id,n])=>`<div class="distribution-row"><span>${this.content.items[id].name}</span><i><b style="width:${n/max*100}%;background:${RARITIES[this.content.items[id].rarity].color}"></b></i><strong>${n.toLocaleString()}</strong></div>`).join('')}`;});
  }else{
   viewport.innerHTML=`<div class="balance-stage"><small>LOCAL DEVELOPMENT ONLY</small><h2>在試煉中，調整世界</h2><p>此工具僅在 npm run dev 啟用。所有操作交由本地伺服器執行。</p><select id="dev-player"><option value="">正在取得在線角色…</option></select><button id="dev-refresh">重新整理角色</button><div class="dev-grid"><button data-dev="invulnerable">無敵 60 秒</button><button data-dev="town">回城</button><button data-dev="boss">前往雷澤</button><button data-dev="resetBoss">重置首領</button><button data-dev="level">升至 Lv. 20</button><button data-dev="heal">補滿氣血靈力</button><button data-dev="give">給予紫霄雷劍</button><button data-dev="spawn">附近生成青狼</button></div><div id="balance-result"></div></div>`;
   this.on('dev-refresh',()=>void this.loadPlayers());void this.loadPlayers();viewport.querySelectorAll<HTMLButtonElement>('[data-dev]').forEach(b=>b.onclick=()=>void this.dev(b.dataset.dev!));
  }
  this.host.querySelector('#editor-hint')!.textContent='平衡工具使用共用規則與固定種子；開發命令不接受一般遊戲連線。';
 }
 private async loadPlayers(){try{const res=await fetch('/api/dev',{headers:{'x-editor-key':this.key}}),data=await res.json();if(!res.ok){this.notice(data.error);return;}this.adminPlayers=data.players;const select=this.host.querySelector<HTMLSelectElement>('#dev-player');if(select)select.innerHTML=this.adminPlayers.map(p=>`<option value="${p.id}">${esc(p.name)} · Lv. ${p.level}</option>`).join('')||'<option value="">請先在另一分頁進入遊戲</option>';}catch{this.notice('無法連線至開發伺服器。');}}
 private async dev(action:string){const player=this.host.querySelector<HTMLSelectElement>('#dev-player')?.value;const res=await fetch('/api/dev',{method:'POST',headers:{'Content-Type':'application/json','x-editor-key':this.key},body:JSON.stringify({action,player})}),data=await res.json();this.notice(res.ok?'已執行：'+action:data.error);}
 private animate=()=>{requestAnimationFrame(this.animate);const now=performance.now(),dt=Math.min(.08,(now-this.last)/1000);this.last=now;this.tickTime+=dt;if(this.tickTime>1/30){this.preview?.update(this.tickTime,now/1000);this.map3d?.update(this.tickTime,now/1000);this.tickTime=0;}};
}
