import type { Game } from '../core/game';
import type { GameEvent,ItemInstance,Snapshot,Slot } from '../../shared/types';
import { distance } from '../../shared/types';
import { ITEMS } from '../../shared/data/equipment';
import { MONSTERS } from '../../shared/data/monsters';
import { LOOT_TABLES } from '../../shared/data/loot-tables';
import { NPCS,REGIONS,WORLD,regionAt } from '../../shared/data/world';
import { RARITIES,SLOTS,STAT_NAMES,PERCENT_STATS } from '../../shared/data/rarities';
import { SKILL_DEFINITIONS } from '../../shared/data/skills';
import { resolveSkillHotbar, weaponCombatIdentity } from '../../shared/combat/weapon-skills';
import { EFFECTS } from '../../shared/data/effects';
import { itemStats } from '../../shared/domains/item';
import { salvageYield } from '../../shared/domains/salvage';
import { ModelPreview } from '../rendering/preview';
import { icon,escapeHtml as esc } from './icons';
import { drawMap } from './map-canvas';
import { FUNCTION_PANEL_IDS,PANEL_DEFINITIONS,panelHotkeyLabel,type PanelId as Panel } from './panel-registry';
import { BODY_PRESETS,CUSTOMIZATION_COUNT,CUSTOM_CONTROLS,FACE_PRESETS,type CustomGroup } from '../character/customization';
import { AVATAR_CANDIDATES,type AvatarCandidateId } from '../character/avatar-candidates';
import { BUILD_DISPLAY } from '../../shared/build-info';
import { resolveInteractionTarget } from '../interaction/interaction-target';
import { CLOUD_RUNTIME } from '../networking/runtime-endpoints';
import { graphicsPresetLabel,presetAllowed,type FixedGraphicsPreset } from '../core/graphics-capability';
import { validateCharacterName } from '../../shared/identity/character-name';
import { activeLocalCharacterToken,clearActiveLocalCharacter,forgetLocalCharacter,legacyCharacterToken,localCharacters,rememberLocalCharacter } from '../identity/local-characters';
export class GameUI {
 root:HTMLElement;panels=new Map<Panel,HTMLElement>();private previews=new Map<Panel,ModelPreview>();private tooltip:HTMLElement;private snap?:Snapshot;private lastRevision=-1;private inventorySelection?:string;private equipmentSlotFilter?:Slot;private equipmentSearch='';private log:{text:string;kind:string}[]=[];private damageLabels:{el:HTMLElement;event:GameEvent;age:number}[]=[];private toastUntil=0;private bestiaryId='wolf';private oldRegion='';private currentNpc='guide';private worldMap?:HTMLCanvasElement;private previewFrame=0;private valueCache=new Map<string,string>();private minimapAt=0;private worldMapAt=0;private buffsSignature='';private interactionSignature='';private hotbarSignature='';private mobileStickPointer:number|null=null;private mobileStickCenterX=0;private mobileStickCenterY=0;private mobileStickRadius=54;private connectionStatus=CLOUD_RUNTIME?'雲端世界':'本地世界';private mapStatus='地圖載入中';private pendingLoginToken='';
 constructor(host:HTMLElement,private game:Game){
  const editorLink=CLOUD_RUNTIME?'':`<a href="/editor">世界工坊 ${icon('arrow')}</a>`;
  const worldMode=this.connectionStatus;
  this.root=document.createElement('div');this.root.id='game-ui';this.root.classList.add('login-active');host.append(this.root);
  this.root.innerHTML=`<div id="vignette"></div><div id="hit-edge"></div>
   <div class="world-brand"><span>Q I N G L A N</span><b>青 嵐 志</b><i>山 海 拾 遺</i></div>
   <section class="player-frame"><div class="avatar">${icon('person')}<b id="player-level">1</b></div><div class="player-vitals"><div class="name-line"><strong id="player-name">行山劍客</strong><span>初入山海</span></div><div class="bar hp"><b id="hp-fill"></b><span id="hp-text"></span></div><div class="bar mp"><b id="mp-fill"></b><span id="mp-text"></span></div><div id="buffs"></div></div></section>
   <section id="target-frame" class="target-frame" hidden><div><span id="target-tag"></span><strong id="target-name"></strong><span id="target-level"></span></div><div class="bar hp"><b id="target-hp"></b><span id="target-hp-text"></span></div><small id="target-state"></small></section>
   <section class="minimap-wrap"><div class="map-heading"><span id="region-name">青嵐宗外院</span><button data-panel="map" title="世界地圖 M">${icon('compass')}</button></div><button class="minimap" data-panel="map" aria-label="開啟世界地圖"><canvas id="minimap" width="220" height="220"></canvas><i class="north">北</i></button><div class="coordinates"><span id="coordinates">—</span><span class="connection-dot" title="${worldMode}"></span><span>青嵐 · 一境</span></div></section>
   <aside class="intel-tracker"><div><i></i>山海見聞<span>◈</span></div><h3 id="explore-title">風起青嵐</h3><p id="explore-copy">尋訪青嵐宗外院的行山客<br>聽聽這片山谷的傳聞</p><button id="guide-shortcut">尋訪沈聽風 <span>↗</span></button></aside>
   <div id="zone-announcement"><small>山 海 之 間 · 萬 物 有 靈</small><strong>青嵐宗外院</strong><i></i></div><div id="flight-status" hidden><b>御劍凌風</b><span><span class="desktop-copy">G</span><span class="touch-copy">御劍鍵</span> 收劍落地</span></div><div id="toast" role="status"></div><div id="interaction-hint"></div><div id="navigation-status" hidden><i>◇</i><span></span><small><span class="desktop-copy">WASD</span><span class="touch-copy">左搖桿</span> 取消導航</small></div>
   <section class="chat"><div class="chat-tabs"><button class="active">綜合</button><span>世界</span><span>見聞</span><span>掉落</span><i>＋</i></div><div id="chat-log"></div><form id="chat-form"><span>世界</span><input id="chat-input" maxlength="180" placeholder="按 Enter 與行者交談…" autocomplete="off"/></form></section>
   <section class="hotbar-wrap"><div class="hotbar-ornament"><i></i><span id="weapon-discipline">器 隨 人 行 · 招 隨 器 變</span><i></i></div><div class="hotbar">${Array.from({length:10},(_,i)=>{const key=String((i+1)%10),potion=i===5;return `<button class="skill ${potion?'':'empty'}" data-skill="${potion?'potion':''}" data-key="${key}" title="${potion?'回元散 · 12 靈石，回復氣血與靈力':''}"><kbd>${key}</kbd>${potion?icon('gourd'):''}<em>${potion?'回元散':''}</em><span class="cooldown"></span></button>`;}).join('')}</div><div class="experience"><b id="xp-fill"></b></div><div class="hotbar-notes"><span>1–4 武器招式 · 5 踏雲 · 6 補給 · 7 傳說專屬</span><span>Tab 選敵 · F 互動 · G 御劍</span></div></section>
   <section id="mobile-controls" aria-label="手機戰鬥操作">
    <div class="mobile-left-controls"><div id="mobile-joystick" class="mobile-joystick" aria-label="移動搖桿"><div class="mobile-joystick-ring"><i class="mobile-joystick-knob"></i></div><span>移動</span></div></div>
    <div class="mobile-right-controls">
     <button id="mobile-context-action" class="mobile-context-action" data-mobile-action="interact" aria-label="拾取或互動" disabled><span class="mobile-context-icon">${icon('bag')}</span><span class="mobile-context-copy"><b>拾取 / 互動</b><small>靠近物品或居民</small></span></button>
     <div class="mobile-utility-row"><button data-mobile-action="jump" aria-label="跳躍">跳</button><button data-mobile-action="flight" aria-label="御劍">御劍</button><button data-skill="potion" data-mobile-action="potion" aria-label="補給">${icon('gourd')}<span class="cooldown"></span></button></div>
     <div class="mobile-skill-cluster"><button class="mobile-skill skill-1 empty" data-mobile-key="1" data-skill="" disabled aria-label="技能一"><em>壹</em><span class="cooldown"></span></button><button class="mobile-skill skill-2 empty" data-mobile-key="2" data-skill="" disabled aria-label="技能二"><em>貳</em><span class="cooldown"></span></button><button class="mobile-skill skill-3 empty" data-mobile-key="3" data-skill="" disabled aria-label="技能三"><em>參</em><span class="cooldown"></span></button><button class="mobile-skill skill-4 empty" data-mobile-key="4" data-skill="" disabled aria-label="技能四"><em>肆</em><span class="cooldown"></span></button><button class="mobile-basic-attack" data-mobile-action="basic" aria-label="普通攻擊">${icon('sword')}<span>攻擊</span></button></div>
    </div>
   </section>
   <button id="mobile-function-toggle" class="mobile-function-toggle" type="button" aria-label="開啟功能選單" aria-expanded="false"><span aria-hidden="true">☰</span><b>功能</b></button><nav class="function-menu">${FUNCTION_PANEL_IDS.map(id=>{const panel=PANEL_DEFINITIONS[id],hotkey=panelHotkeyLabel(panel);return `<button data-panel="${id}" title="${panel.menuLabel??panel.title} ${hotkey}">${icon(panel.icon)}<span>${panel.menuLabel??panel.title}</span><kbd>${hotkey}</kbd></button>`;}).join('')}</nav>
   <div id="death-screen" hidden><small>靈 息 未 散</small><h2>此行，暫歇</h2><p>身上裝備損失 5 點耐久，所有物品保留。</p><button id="revive-town" class="primary">回青嵐宗外院</button><button id="revive-here">原地凝魂</button></div>
   <section id="login-screen"><div class="login-top"><span>QINGLAN CHRONICLES</span>${editorLink}</div><div class="login-title"><div class="seal">山<br>海</div><span>一 劍 入 山 海</span><h1>青嵐志</h1><h2>山 海 拾 遺</h2><p>循風入谷，聽雷尋寶。<br>每一件靈器，都是一段未完的遠行。</p></div><div class="character-login"><section class="character-roster"><header><span>此裝置角色</span><small>選擇既有角色繼續旅程</small></header><div id="character-list"></div></section><form id="login-form"><label>建立新角色</label><input id="login-name" value="" maxlength="16" autocomplete="off" autocapitalize="off" spellcheck="false" enterkeyhint="done" autofocus placeholder="輸入 2～16 字角色名稱" aria-label="新角色名稱"/><button class="primary" type="submit">建 立 角 色 <span>→</span></button><small>${worldMode} · 名稱全世界不得重複 · 進度自動保存</small></form><p id="login-message" role="status">選擇既有角色繼續旅程，或建立新的角色。除非網址帶有 autoresume=1，否則首頁不會自動跳過。</p></div><div class="login-footer"><span>探索 / 異獸 / 靈器 / 交易</span><span>桌機 WASD / 手機左搖桿移動 · 右側拖曳轉動視角</span></div></section>`;
  this.tooltip=document.createElement('div');this.tooltip.className='item-tooltip';this.tooltip.hidden=true;this.root.append(this.tooltip);
  this.setupMobileControls();
  this.root.addEventListener('click',e=>{const target=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-panel]');if(target){e.preventDefault();e.stopPropagation();this.root.classList.remove('mobile-menu-open');this.root.querySelector<HTMLButtonElement>('#mobile-function-toggle')?.setAttribute('aria-expanded','false');this.toggle(target.dataset.panel as Panel);}});
  this.root.querySelectorAll<HTMLButtonElement>('[data-skill]').forEach(b=>b.onclick=()=>{if(b.dataset.skill==='potion')game.command({type:'potion'});else if(b.dataset.skill)game.command({type:'attack',skill:b.dataset.skill});});
  this.renderLoginCharacters();
  const autoResumeToken=activeLocalCharacterToken();
  const allowAutoResume=new URLSearchParams(location.search).get('autoresume')==='1';
  if(allowAutoResume&&autoResumeToken)queueMicrotask(()=>{if(this.root.querySelector('#login-screen')&&!this.pendingLoginToken){this.pendingLoginToken=autoResumeToken;this.setLoginBusy(true,'正在恢復本裝置上次登入的角色…');this.game.resumeCharacter(autoResumeToken);}});
  const loginName=this.root.querySelector<HTMLInputElement>('#login-name')!;
  // HF17.2: desktop text entry is an explicit UI input island. Never let gameplay keyboard/pointer handlers consume IME or normal typing.
  for(const eventName of ['keydown','keyup','keypress','beforeinput','compositionstart','compositionupdate','compositionend'] as const)loginName.addEventListener(eventName,e=>e.stopPropagation());
  loginName.addEventListener('pointerdown',e=>e.stopPropagation());loginName.addEventListener('click',e=>e.stopPropagation());
  if(matchMedia('(pointer: fine)').matches)requestAnimationFrame(()=>{if(!loginName.readOnly)loginName.focus({preventScroll:true});});
  this.root.querySelector<HTMLFormElement>('#login-form')!.onsubmit=e=>{e.preventDefault();const input=this.root.querySelector<HTMLInputElement>('#login-name')!,validated=validateCharacterName(input.value);if(!validated.ok){this.loginError(validated.message,validated.code);input.focus({preventScroll:true});return;}this.pendingLoginToken='';this.setLoginBusy(true,'正在向世界確認角色名稱…');game.createCharacter(validated.name);};
  this.root.querySelector<HTMLFormElement>('#chat-form')!.onsubmit=e=>{e.preventDefault();const input=this.root.querySelector<HTMLInputElement>('#chat-input')!;if(input.value.trim())game.command({type:'chat',text:input.value});input.value='';input.blur();};
  this.root.querySelector<HTMLButtonElement>('#guide-shortcut')!.onclick=()=>game.interact('guide');
  this.root.querySelector<HTMLButtonElement>('#revive-town')!.onclick=()=>game.command({type:'revive',town:true});this.root.querySelector<HTMLButtonElement>('#revive-here')!.onclick=()=>game.command({type:'revive',town:false});
  window.addEventListener('qinglan-map-ready',this.onMapReady);
  this.appendLog('山海不設歸途。先到沈聽風身旁，按 F 詢問異獸情報。','system');
 }
 private renderLoginCharacters(){
  const list=this.root.querySelector<HTMLElement>('#character-list');if(!list)return;const records=localCharacters(),legacy=legacyCharacterToken(),knownTokens=new Set(records.map(r=>r.token));
  const cards=records.map(r=>`<button type="button" class="character-card" data-character-token="${esc(r.token)}"><span><b>${esc(r.name)}</b><small>上次遊玩 ${new Date(r.lastPlayedAt).toLocaleDateString()}</small></span><em>登入 →</em></button>`);
  if(legacy&&!knownTokens.has(legacy))cards.push(`<button type="button" class="character-card legacy" data-character-token="${esc(legacy)}"><span><b>舊版角色資料</b><small>首次載入後會顯示正式角色名稱</small></span><em>載入 →</em></button>`);
  list.innerHTML=cards.join('')||'<div class="character-empty">這台裝置尚未保存角色。<br>請在下方建立第一位行者。</div>';
  list.querySelectorAll<HTMLButtonElement>('[data-character-token]').forEach(button=>button.onclick=()=>{const token=button.dataset.characterToken!;this.pendingLoginToken=token;this.setLoginBusy(true,'正在載入角色資料…');this.game.resumeCharacter(token);});
 }
 private setLoginBusy(busy:boolean,message:string){const login=this.root.querySelector<HTMLElement>('#login-screen');if(!login)return;login.classList.toggle('login-busy',busy);login.setAttribute('aria-busy',String(busy));login.querySelectorAll<HTMLButtonElement>('button').forEach(button=>button.disabled=busy);const input=login.querySelector<HTMLInputElement>('#login-name');if(input){input.readOnly=busy;input.setAttribute('aria-disabled',String(busy));if(!busy&&matchMedia('(pointer: fine)').matches)requestAnimationFrame(()=>input.focus({preventScroll:true}));}const status=login.querySelector<HTMLElement>('#login-message');if(status){status.textContent=message;status.classList.remove('error');}}
 loginError(text:string,code=''){if(code==='CHARACTER_SESSION_INVALID'&&this.pendingLoginToken){forgetLocalCharacter(this.pendingLoginToken);this.pendingLoginToken='';this.renderLoginCharacters();}this.setLoginBusy(false,text);const status=this.root.querySelector<HTMLElement>('#login-message');status?.classList.add('error');}
 completeCharacterLogin(id:string,name:string,token:string){if(token)rememberLocalCharacter({id,name,token,lastPlayedAt:Date.now()});this.pendingLoginToken='';const login=this.root.querySelector<HTMLElement>('#login-screen');if(!login)return;this.setLoginBusy(false,`歡迎回來，${name}`);this.root.classList.remove('login-active');login.classList.add('departing');login.style.pointerEvents='none';setTimeout(()=>login.remove(),650);}

 private setupMobileControls(){
  const touchCapable=matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0;this.root.classList.toggle('touch-controls',touchCapable);
  const menuToggle=this.root.querySelector<HTMLButtonElement>('#mobile-function-toggle');if(menuToggle){menuToggle.onclick=e=>{e.preventDefault();e.stopPropagation();const open=this.root.classList.toggle('mobile-menu-open');menuToggle.setAttribute('aria-expanded',String(open));if(open)this.game.stopMobileMovement();};}
  const zone=this.root.querySelector<HTMLElement>('#mobile-joystick')!,knob=zone.querySelector<HTMLElement>('.mobile-joystick-knob')!;
  const update=(e:PointerEvent)=>{const dx=e.clientX-this.mobileStickCenterX,dy=e.clientY-this.mobileStickCenterY,radius=this.mobileStickRadius,length=Math.hypot(dx,dy),scale=length>radius?radius/length:1,nx=dx*scale/radius,ny=dy*scale/radius,magnitude=Math.min(1,length/radius),deadzone=.14,strength=magnitude<=deadzone?0:(magnitude-deadzone)/(1-deadzone),directionLength=Math.hypot(nx,ny)||1;knob.style.transform=`translate(${nx*radius*.58}px,${ny*radius*.58}px)`;this.game.setMobileMovement(nx/directionLength*strength,ny/directionLength*strength,magnitude>.82);};
  zone.onpointerdown=e=>{if(this.mobileStickPointer!==null)return;const rect=zone.getBoundingClientRect();this.mobileStickCenterX=rect.left+rect.width/2;this.mobileStickCenterY=rect.top+rect.height/2;this.mobileStickRadius=Math.max(34,rect.width*.34);this.mobileStickPointer=e.pointerId;zone.setPointerCapture(e.pointerId);update(e);e.preventDefault();e.stopPropagation();};
  zone.onpointermove=e=>{if(e.pointerId===this.mobileStickPointer){update(e);e.preventDefault();e.stopPropagation();}};
  const release=(e:PointerEvent)=>{if(e.pointerId!==this.mobileStickPointer)return;this.mobileStickPointer=null;knob.style.transform='translate(0,0)';this.game.stopMobileMovement();e.preventDefault();e.stopPropagation();};zone.onpointerup=release;zone.onpointercancel=release;
  this.root.querySelectorAll<HTMLButtonElement>('[data-mobile-action]').forEach(button=>{button.onclick=e=>{e.preventDefault();e.stopPropagation();const action=button.dataset.mobileAction;if(action==='basic')this.game.mobileBasicAttack();else if(action==='jump')this.game.mobileJump();else if(action==='flight')this.game.mobileFlight();else if(action==='interact')this.game.mobileInteract();else if(action==='potion')this.game.command({type:'potion'});};});
  addEventListener('orientationchange',()=>this.game.stopMobileMovement());
 }
 private onMapReady=(event:Event)=>{const detail=(event as CustomEvent<{source?:string;collision?:string;terrain?:string}>).detail,source=detail?.source==='uploaded-xianxia-glb'?'自訂仙俠 GLB 地圖':'世界場景',parts=[source,detail?.collision,detail?.terrain].filter((value):value is string=>!!value);this.mapStatus=parts.join(' · ');const el=this.panels.get('settings')?.querySelector<HTMLElement>('#settings-map-status');if(el)el.textContent=this.mapStatus;};
 status(text:string){this.connectionStatus=text;const el=this.panels.get('settings')?.querySelector<HTMLElement>('#settings-connection-status');if(el)el.textContent=text;}
 runtimeError(text:string){this.toast(text);let el=this.root.querySelector<HTMLElement>('#runtime-warning');if(!el){el=document.createElement('div');el.id='runtime-warning';this.root.append(el);}el.textContent=text;el.onclick=()=>el.remove();}
 focusChat(){this.root.querySelector<HTMLInputElement>('#chat-input')!.focus();}
 openSettings(){if(!this.panels.has('settings'))this.toggle('settings');}
 toast(text:string){this.root.querySelector('#toast')!.textContent=text;this.root.querySelector('#toast')!.classList.add('visible');this.toastUntil=performance.now()+3600;}
 impact(){const edge=this.root.querySelector('#hit-edge')!;edge.classList.remove('impact');void (edge as HTMLElement).offsetWidth;edge.classList.add('impact');}
 damage(event:GameEvent){if(event.x===undefined||event.z===undefined)return;const el=document.createElement('div');el.className=`damage-number ${event.critical?'critical':''} ${event.value!<0?'healing':''}`;el.textContent=event.value===0?'閃避':`${event.critical?'✧ ':''}${Math.abs(event.value??0)}`;this.root.append(el);this.damageLabels.push({el,event,age:0});}
 private appendLog(text:string,kind='system'){this.log.push({text,kind});this.log=this.log.slice(-35);const el=this.root.querySelector('#chat-log')!;el.innerHTML=this.log.slice(-6).map(l=>`<p class="${l.kind}"><span>◆</span> ${esc(l.text)}</p>`).join('');el.scrollTop=el.scrollHeight;}
 private setText(selector:string,value:string){const key='t:'+selector;if(this.valueCache.get(key)===value)return;this.valueCache.set(key,value);this.root.querySelector(selector)!.textContent=value;}
 private setWidth(selector:string,value:string){const key='w:'+selector;if(this.valueCache.get(key)===value)return;this.valueCache.set(key,value);(this.root.querySelector(selector) as HTMLElement).style.width=value;}
 private updateHotbar(s:Snapshot){
  const loadout=resolveSkillHotbar(s.self.equipment),identity=weaponCombatIdentity(s.self.equipment),signature=loadout.map(x=>`${x.key}:${x.skillId}`).join('|');if(signature===this.hotbarSignature)return;this.hotbarSignature=signature;
  const byKey=new Map(loadout.map(x=>[x.key,x] as const));
  this.root.querySelectorAll<HTMLButtonElement>('.hotbar [data-key]').forEach(button=>{const key=button.dataset.key!,entry=byKey.get(key),potion=key==='6',skill=entry?SKILL_DEFINITIONS[entry.skillId]:undefined;button.dataset.skill=potion?'potion':entry?.skillId??'';button.classList.toggle('empty',!potion&&!skill);button.classList.toggle('legendary-skill',!!entry?.legendary);const displayName=entry?.label??skill?.name??'';button.title=potion?'回元散 · 12 靈石，回復氣血與靈力':skill?`${displayName} · ${skill.description}`:'';button.querySelector('em')!.textContent=potion?'回元散':displayName;const kbd=button.querySelector('kbd')!.outerHTML,cd='<span class="cooldown"></span>';button.innerHTML=kbd+(potion?icon('gourd'):skill?icon(skill.icon):'')+`<em>${potion?'回元散':displayName}</em>${cd}`;});
  this.root.querySelectorAll<HTMLButtonElement>('[data-mobile-key]').forEach(button=>{const key=button.dataset.mobileKey!,entry=byKey.get(key),skill=entry?SKILL_DEFINITIONS[entry.skillId]:undefined,displayName=entry?.label??skill?.name??'';button.dataset.skill=entry?.skillId??'';button.classList.toggle('empty',!skill);button.classList.toggle('legendary-skill',!!entry?.legendary);button.disabled=!skill;button.title=skill?`${displayName} · ${skill.description}`:'尚未配置技能';button.innerHTML=(skill?icon(skill.icon):'')+`<em>${skill?displayName:key}</em><span class="cooldown"></span>`;});
  const weapon=identity.baseId?ITEMS[identity.baseId]:undefined,discipline=this.root.querySelector('#weapon-discipline');if(discipline)discipline.textContent=weapon?`${weapon.name} · ${identity.profile.toUpperCase()} 招式${identity.legendarySkillId?' · 傳說專屬已解鎖':''}`:'徒手 · 劍式基礎';
 }
 update(s:Snapshot){
  this.snap=s;const p=s.self;this.updateHotbar(s);const set=(selector:string,value:string)=>this.setText(selector,value);
  set('#player-name',p.name);set('#player-level',String(p.level));set('#hp-text',`${Math.ceil(p.hp)} / ${p.maxHp}`);set('#mp-text',`${Math.floor(p.mp)} / ${p.maxMp}`);
  this.setWidth('#hp-fill',`${p.hp/p.maxHp*100}%`);this.setWidth('#mp-fill',`${p.mp/p.maxMp*100}%`);this.setWidth('#xp-fill',`${p.xp/(p.level*95)*100}%`);
  const target=s.monsters.find(m=>m.id===p.target&&m.hp>0),targetEl=this.root.querySelector<HTMLElement>('#target-frame')!;targetEl.hidden=!target;
  if(target){const def=MONSTERS[target.defId],status=(target.effects??[]).map(e=>EFFECTS[e.id]?.name).filter(Boolean).slice(0,3).join(' · ');set('#target-tag',def.aiProfile==='boss'?'首 領':'異 獸');set('#target-name',def.name);set('#target-level',`Lv. ${def.level}`);set('#target-hp-text',`${Math.ceil(target.hp)} / ${target.maxHp}`);this.setWidth('#target-hp',`${target.hp/target.maxHp*100}%`);set('#target-state',target.attack?'正在蓄力 · 注意範圍與方向預警':status?`${status} · ${def.element}屬性`:`${def.element}屬性 · ${def.aiProfile==='passive'?'性情溫和':'保持警覺'}`);}
  const buffHtml=(p.effects??[]).map(e=>`<span title="${esc(EFFECTS[e.id]?.name)}" style="border-color:${EFFECTS[e.id]?.color}">${esc(EFFECTS[e.id]?.name)} <small>${Math.ceil(e.expires-s.time)}</small></span>`).join('');if(buffHtml!==this.buffsSignature){this.buffsSignature=buffHtml;this.root.querySelector<HTMLElement>('#buffs')!.innerHTML=buffHtml;}
  const region=regionAt(p);set('#region-name',region.name);set('#coordinates',`${Math.round(p.x)}, ${Math.round(p.z)}`);const now=performance.now(),minimapInterval=1000/this.game.graphics.minimapFps;if(!this.root.classList.contains('touch-controls')&&now-this.minimapAt>minimapInterval){this.minimapAt=now;drawMap(this.root.querySelector<HTMLCanvasElement>('#minimap')!,s,true);}
  if(region.id!==this.oldRegion){this.oldRegion=region.id;const zone=this.root.querySelector<HTMLElement>('#zone-announcement')!;zone.querySelector('strong')!.textContent=region.name;zone.classList.remove('show');void zone.offsetWidth;zone.classList.add('show');set('#explore-title',region.name);this.root.querySelector('#explore-copy')!.textContent=region.description;}
  const nav=this.root.querySelector<HTMLElement>('#navigation-status')!;nav.hidden=!p.path.length;if(p.path.length)nav.querySelector('span')!.textContent=`循路前往 · ${p.navLabel??'選定位置'}`;
  this.root.querySelector<HTMLElement>('#death-screen')!.hidden=p.hp>0;this.root.classList.toggle('player-dead',p.hp<=0);if(p.hp<=0)this.game.stopMobileMovement();
  const interactionTarget=resolveInteractionTarget(s),touch=this.root.classList.contains('touch-controls'),hotkey='<kbd>F</kbd>',interaction=touch?'':interactionTarget?.type==='drop'?`${hotkey} 拾取物品`:interactionTarget?.type==='npc'?`${hotkey} 與 ${esc(interactionTarget.name)} 交談`:'';if(interaction!==this.interactionSignature){this.interactionSignature=interaction;this.root.querySelector('#interaction-hint')!.innerHTML=interaction;}
  const mobileContext=this.root.querySelector<HTMLButtonElement>('#mobile-context-action');if(mobileContext){const copy=mobileContext.querySelector<HTMLElement>('.mobile-context-copy')!,title=copy.querySelector('b')!,detail=copy.querySelector('small')!;mobileContext.disabled=!interactionTarget;mobileContext.classList.toggle('pickup-ready',interactionTarget?.type==='drop');mobileContext.classList.toggle('npc-ready',interactionTarget?.type==='npc');if(interactionTarget?.type==='drop'){const drop=s.drops.find(d=>d.id===interactionTarget.id);title.textContent='拾取物品';detail.textContent=drop?ITEMS[drop.item.baseId]?.name??'附近靈物':'附近靈物';mobileContext.setAttribute('aria-label',`拾取 ${detail.textContent}`);}else if(interactionTarget?.type==='npc'){title.textContent='交談';detail.textContent=interactionTarget.name;mobileContext.setAttribute('aria-label',`與 ${interactionTarget.name} 交談`);}else{title.textContent='拾取 / 互動';detail.textContent='靠近物品或居民';mobileContext.setAttribute('aria-label','拾取或互動');}}
  for(const event of s.events){if(event.type==='notice'||event.type==='trade'){this.toast(event.text??'');this.appendLog(event.text??'');}if(event.type==='chat')this.appendLog(event.text??'','world');if(event.type==='pickup'){this.toast(`收入行囊 · ${event.text}`);this.appendLog(`拾取 ${event.text}`,'rarity-'+event.rarity);}if(event.type==='drop'&&RARITIES[event.rarity!]?.rank>=4)this.toast(`靈光乍現 · ${event.text}`);if(event.type==='level'){this.toast(event.text!);this.appendLog(event.text!);}}
  if(p.revision!==this.lastRevision){this.lastRevision=p.revision;if(this.panels.has('inventory'))this.renderInventory();if(this.panels.has('equipment'))this.renderEquipment();if(this.panels.has('bestiary'))this.renderBestiary();}
  if(this.panels.has('market'))this.renderMarket(false);
  if(s.trade){if(!this.panels.has('trade'))this.createPanel('trade','行者交易','雙方鎖定 · 雙方確認');this.renderTrade();}else if(this.panels.has('trade'))this.close('trade');
  if(this.worldMap&&now-this.worldMapAt>250){this.worldMapAt=now;drawMap(this.worldMap,s);}
 }
 toggle(panel:Panel){if(this.panels.has(panel)){this.close(panel);return;}if(!this.snap&&panel!=='settings'){this.toast('世界資料尚未同步；設定仍可使用。');return;}
  const definition=PANEL_DEFINITIONS[panel];
  this.createPanel(panel,definition.title,definition.subtitle);if(panel==='inventory')this.renderInventory();if(panel==='equipment')this.renderEquipment();if(panel==='creator')this.renderCreator();if(panel==='map')this.renderMap();if(panel==='bestiary')this.renderBestiary();if(panel==='market')this.renderMarket(true);if(panel==='settings')this.renderSettings();
 }
 private createPanel(panel:Panel,title:string,subtitle:string){const el=document.createElement('section');el.className=`game-panel panel-${panel}`;el.innerHTML=`<header><div><h2>${title}</h2><span>${subtitle}</span></div><button class="close-panel" title="關閉">${icon('close')}</button></header><div class="panel-body"></div>`;el.querySelector<HTMLButtonElement>('.close-panel')!.onclick=()=>this.close(panel);this.root.append(el);this.makePanelDraggable(el);this.panels.set(panel,el);this.root.classList.add('panel-open');this.game.stopMobileMovement();return el;}
 private makePanelDraggable(panel:HTMLElement){
  const header=panel.querySelector<HTMLElement>('header');if(!header)return;panel.classList.add('panel-draggable');let pointerId:number|null=null,startX=0,startY=0,startLeft=0,startTop=0;
  const viewport=()=>{const v=window.visualViewport;return {left:v?.offsetLeft??0,top:v?.offsetTop??0,width:v?.width??innerWidth,height:v?.height??innerHeight};};
  const place=(left:number,top:number)=>{const v=viewport(),rect=panel.getBoundingClientRect(),margin=6,maxLeft=v.left+Math.max(margin,v.width-rect.width-margin),maxTop=v.top+Math.max(margin,v.height-rect.height-margin);panel.style.setProperty('--panel-left',`${Math.min(maxLeft,Math.max(v.left+margin,left))}px`);panel.style.setProperty('--panel-top',`${Math.min(maxTop,Math.max(v.top+margin,top))}px`);};
  const finish=(e:PointerEvent)=>{if(pointerId!==e.pointerId)return;pointerId=null;panel.classList.remove('panel-dragging');if(header.hasPointerCapture(e.pointerId))header.releasePointerCapture(e.pointerId);};
  header.addEventListener('pointerdown',e=>{if((e.target as HTMLElement).closest('button,a,input,select,textarea,label'))return;if(e.pointerType==='mouse'&&e.button!==0)return;const rect=panel.getBoundingClientRect();pointerId=e.pointerId;startX=e.clientX;startY=e.clientY;startLeft=rect.left;startTop=rect.top;panel.classList.add('panel-dragged','panel-dragging');place(startLeft,startTop);header.setPointerCapture(e.pointerId);e.preventDefault();});
  header.addEventListener('pointermove',e=>{if(pointerId!==e.pointerId)return;place(startLeft+(e.clientX-startX),startTop+(e.clientY-startY));e.preventDefault();});
  header.addEventListener('pointerup',finish);header.addEventListener('pointercancel',finish);
 }
 close(panel:Panel){if(panel==='creator'){this.game.setSelfEquipmentPreview(false);this.game.setCharacterCreatorView('none');}this.previews.get(panel)?.dispose();this.previews.delete(panel);this.panels.get(panel)?.remove();this.panels.delete(panel);this.root.classList.toggle('panel-open',this.panels.size>0);this.tooltip.hidden=true;if(panel==='map')this.worldMap=undefined;if(panel==='trade')this.game.command({type:'tradeCancel'});}
 closeAll(){for(const p of [...this.panels.keys()])this.close(p);}
 private body(panel:Panel){return this.panels.get(panel)!.querySelector<HTMLElement>('.panel-body')!;}
 private itemCell(item:ItemInstance,extra=''){const base=ITEMS[item.baseId],r=RARITIES[item.rarity];return `<button class="item-cell ${extra} ${this.inventorySelection===item.id?'selected':''}" data-item="${item.id}" draggable="true" style="--rarity:${r.color}" aria-label="${esc(base.name)}">${icon(base.icon)}${!item.identified?'<i class="unknown">?</i>':''}${item.quantity>1?`<span class="stack">${item.quantity}</span>`:''}${item.enhancementLevel?`<span class="enhancement">+${item.enhancementLevel}</span>`:''}</button>`;}
 private bindItems(parent:HTMLElement){parent.querySelectorAll<HTMLElement>('[data-item]').forEach(cell=>{
  const id=cell.dataset.item!,inventoryItem=this.snap!.self.inventory.find(i=>i.id===id),item=inventoryItem??Object.values(this.snap!.self.equipment).find(i=>i?.id===id);if(!item)return;
  cell.onmouseenter=()=>this.showTooltip(item,cell);cell.onmouseleave=()=>this.tooltip.hidden=true;
  cell.ondragstart=e=>{if(!inventoryItem){e.preventDefault();return;}e.dataTransfer!.setData('text/item-id',id);this.tooltip.hidden=true;};
  cell.onclick=e=>{e.stopPropagation();this.inventorySelection=id;if(this.panels.has('inventory'))this.renderInventory();if(this.panels.has('equipment'))this.renderEquipmentInventoryPane();};
  cell.ondblclick=e=>{e.stopPropagation();const slot=ITEMS[item.baseId].slot;if(inventoryItem){if(!item.identified)this.game.command({type:'identify',id});else if(slot)this.game.command({type:'equip',id});}else if(slot)this.game.command({type:'unequip',slot});};
 });}
 private renderInventory(){
  const p=this.snap!.self,body=this.body('inventory'),previousScroll=body.querySelector<HTMLElement>('.inventory-scroll')?.scrollTop??0,selected=p.inventory.find(i=>i.id===this.inventorySelection),selectedBase=selected?ITEMS[selected.baseId]:undefined,salvage=selected?salvageYield(selected):0;body.innerHTML=`<div class="inventory-shell"><div class="inventory-scroll"><div class="inventory-summary"><span>隨身行囊</span><span>${p.inventory.length} / 48</span></div><div class="inventory-grid">${p.inventory.map(i=>this.itemCell(i)).join('')}${Array.from({length:48-p.inventory.length},()=>'<div class="item-cell vacant"><i>·</i></div>').join('')}</div><div class="inventory-tip">雙擊穿戴 / 鑑定 · 拖曳至裝備部位 · 選取後可丟棄、分解或永久銷毀</div></div><div class="inventory-actions-dock"><div class="selected-item">${selected?`<strong style="color:${RARITIES[selected.rarity].color}">${esc(selectedBase!.name)}</strong><div class="inventory-primary-actions"><button id="item-equip" ${selectedBase!.slot?'':'disabled'}>${selectedBase!.slot?(selected.identified?'穿戴':'鑑定'):'不可裝備'}</button><button id="item-list">上架市集</button><button id="item-enhance" ${selectedBase!.slot?'':'disabled'}>強化</button></div><div class="inventory-dispose-actions"><button id="item-drop">丟到地上</button>${salvage>0?`<button id="item-salvage">分解 → 精鍊靈砂 ×${salvage}</button>`:''}<button id="item-destroy" class="danger">永久銷毀</button></div>`:'<span>選取物品，查看可用操作</span>'}</div><footer><span class="currency">${icon('coin')} ${p.gold.toLocaleString()} <small>靈石</small></span><button id="open-gear">${esc(PANEL_DEFINITIONS.equipment.menuLabel??PANEL_DEFINITIONS.equipment.title)}</button></footer></div></div>`;const inventoryScroll=body.querySelector<HTMLElement>('.inventory-scroll');if(inventoryScroll)inventoryScroll.scrollTop=previousScroll;
  this.bindItems(body);body.querySelector<HTMLButtonElement>('#open-gear')!.onclick=()=>{if(!this.panels.has('equipment'))this.toggle('equipment');};
  if(selected){const base=ITEMS[selected.baseId],equipButton=body.querySelector<HTMLButtonElement>('#item-equip');if(equipButton&&base.slot)equipButton.onclick=()=>this.game.command({type:selected.identified?'equip':'identify',id:selected.id});body.querySelector<HTMLButtonElement>('#item-list')!.onclick=()=>{if(!this.panels.has('market'))this.toggle('market');};const enhanceButton=body.querySelector<HTMLButtonElement>('#item-enhance');if(enhanceButton&&base.slot)enhanceButton.onclick=()=>this.game.command({type:'enhance',id:selected.id});body.querySelector<HTMLButtonElement>('#item-drop')!.onclick=()=>{if(confirm(`將「${base.name}」丟到角色前方？\n五分鐘內仍可拾回。`))this.game.command({type:'discard',id:selected.id});};const salvageButton=body.querySelector<HTMLButtonElement>('#item-salvage');if(salvageButton)salvageButton.onclick=()=>{const amount=salvageYield(selected);if(confirm(`確定分解「${base.name}」？\n裝備將消失並轉化為精鍊靈砂 ×${amount}。`))this.game.command({type:'salvage',id:selected.id});};body.querySelector<HTMLButtonElement>('#item-destroy')!.onclick=()=>{if(confirm(`永久銷毀「${base.name}」？\n此操作不會產生材料，也無法復原。`))this.game.command({type:'destroy',id:selected.id});};}
 }
 private renderEquipment(){
  const p=this.snap!.self,body=this.body('equipment');if(!body.querySelector('.gw2-equipment-shell')){
   body.innerHTML=`<div class="gw2-equipment-shell"><aside class="equipment-inventory-pane"><div class="equipment-inventory-heading"><strong>裝備庫</strong><span>雙擊穿戴 · 拖曳至部位</span></div><div class="equipment-search-row"><input id="equipment-search" type="search" placeholder="搜尋裝備名稱…" autocomplete="off"/><button id="equipment-filter-clear" title="顯示所有裝備">全部</button></div><div class="equipment-filter-state"><span>所有可穿戴裝備</span><b></b></div><div class="equipment-inventory-grid"></div><div class="equipment-candidate-actions"></div></aside><section class="equipment-character-pane"><div class="character-heading"><strong>${esc(p.name)}</strong><span>Lv. ${p.level} · 行山劍客</span></div><div class="equipment-stage"><div class="equipment-side left"></div><div class="character-preview"></div><div class="equipment-side right"></div><div class="preview-floor"></div></div><div class="character-stats"></div><div class="equipment-footnote">點擊部位篩選左側可用裝備 · 拖曳裝備到部位 · 雙擊裝備快速穿戴／卸下 <button id="unequip-body">卸下全身（保留武器）</button></div></section></div>`;
   const search=body.querySelector<HTMLInputElement>('#equipment-search')!;search.value=this.equipmentSearch;search.oninput=()=>{this.equipmentSearch=search.value;this.renderEquipmentInventoryPane();};body.querySelector<HTMLButtonElement>('#equipment-filter-clear')!.onclick=()=>{this.equipmentSlotFilter=undefined;this.renderEquipment();};
   if(this.game.graphics.previews){const preview=new ModelPreview(body.querySelector<HTMLElement>('.character-preview')!);this.previews.set('equipment',preview);}else body.querySelector<HTMLElement>('.character-preview')!.innerHTML='<div class="preview-disabled">3D 預覽已關閉</div>';
  }
  const slots=Object.keys(SLOTS) as Slot[];for(const [side,list] of [['left',slots.slice(0,9)],['right',slots.slice(9)]] as const){const column=body.querySelector<HTMLElement>(`.equipment-side.${side}`)!;column.innerHTML=list.map(slot=>`<div class="equipment-slot ${this.equipmentSlotFilter===slot?'filter-active':''}" data-slot="${slot}">${p.equipment[slot]?this.itemCell(p.equipment[slot]!):`<div class="empty-slot">${icon(slot==='mainhand'?'sword':slot==='head'?'crown':slot==='chest'?'robe':'crystal')}</div>`}<button class="equipment-slot-filter" data-slot-filter="${slot}" title="只顯示可裝備於${SLOTS[slot]}的物品">${SLOTS[slot]}</button></div>`).join('');column.querySelectorAll<HTMLElement>('[data-slot]').forEach(el=>{el.ondragover=e=>{e.preventDefault();el.classList.add('drag-over');};el.ondragleave=()=>el.classList.remove('drag-over');el.ondrop=e=>{e.preventDefault();el.classList.remove('drag-over');const id=e.dataTransfer!.getData('text/item-id'),item=p.inventory.find(i=>i.id===id);if(item&&ITEMS[item.baseId].slot===el.dataset.slot)this.game.command({type:'equip',id});else this.toast('裝備部位不符。');};});column.querySelectorAll<HTMLButtonElement>('[data-slot-filter]').forEach(button=>button.onclick=e=>{e.stopPropagation();const slot=button.dataset.slotFilter as Slot;this.equipmentSlotFilter=this.equipmentSlotFilter===slot?undefined:slot;this.renderEquipment();});}
  this.bindItems(body);body.querySelector('.character-stats')!.innerHTML=(['attack','defense','hp','crit','haste','lightningResist'] as const).map(k=>`<div><span>${STAT_NAMES[k]}</span><b>${Math.round(p.stats[k])}${PERCENT_STATS.has(k)?'%':''}</b></div>`).join('');body.querySelector('.character-heading span')!.textContent=`Lv. ${p.level} · 行山劍客`;this.previews.get('equipment')?.setCharacter(p.equipment,undefined,this.game.getCharacterCustomization());const unequipBody=body.querySelector<HTMLButtonElement>('#unequip-body');if(unequipBody)unequipBody.onclick=()=>{for(const slot of (Object.keys(SLOTS) as Slot[]))if(slot!=='mainhand'&&p.equipment[slot])this.game.command({type:'unequip',slot});};this.renderEquipmentInventoryPane();
 }
 private renderEquipmentInventoryPane(){
  if(!this.snap||!this.panels.has('equipment'))return;const body=this.body('equipment'),grid=body.querySelector<HTMLElement>('.equipment-inventory-grid'),state=body.querySelector<HTMLElement>('.equipment-filter-state'),actions=body.querySelector<HTMLElement>('.equipment-candidate-actions');if(!grid||!state||!actions)return;const p=this.snap.self,query=this.equipmentSearch.trim().toLocaleLowerCase('zh-Hant'),compatible=p.inventory.filter(item=>{const base=ITEMS[item.baseId];if(!base.slot)return false;if(this.equipmentSlotFilter&&base.slot!==this.equipmentSlotFilter)return false;if(query&&!base.name.toLocaleLowerCase('zh-Hant').includes(query))return false;return true;}).sort((a,b)=>RARITIES[b.rarity].rank-RARITIES[a.rarity].rank||ITEMS[a.baseId].name.localeCompare(ITEMS[b.baseId].name,'zh-Hant'));
  state.querySelector('span')!.textContent=this.equipmentSlotFilter?`可裝備於：${SLOTS[this.equipmentSlotFilter]}`:'所有可穿戴裝備';state.querySelector('b')!.textContent=`${compatible.length} 件`;body.querySelectorAll('.equipment-slot').forEach(el=>el.classList.toggle('filter-active',(el as HTMLElement).dataset.slot===this.equipmentSlotFilter));grid.innerHTML=compatible.length?compatible.map(item=>this.itemCell(item,'equipment-candidate')).join(''):'<div class="equipment-empty-state">沒有符合條件的裝備</div>';const selected=compatible.find(item=>item.id===this.inventorySelection),base=selected?ITEMS[selected.baseId]:undefined,equipped=selected&&base?.slot?p.equipment[base.slot]:undefined;if(selected&&base?.slot){const next=itemStats(selected),current=equipped?itemStats(equipped):undefined,diffs=(Object.keys(next) as (keyof typeof next)[]).map(key=>({key,diff:current?next[key]-current[key]:next[key]})).filter(x=>Math.abs(x.diff)>.001).slice(0,4),compare=diffs.length?`<div class="equipment-inline-compare">${diffs.map(x=>`<span class="${x.diff>=0?'up':'down'}">${STAT_NAMES[x.key]} ${x.diff>=0?'+':''}${Math.round(x.diff)}${PERCENT_STATS.has(x.key)?'%':''}</span>`).join('')}</div>`:'<div class="equipment-inline-compare neutral">主要屬性與目前裝備相近</div>';actions.innerHTML=`<div class="equipment-selection-summary"><strong style="color:${RARITIES[selected.rarity].color}">${esc(base.name)}</strong><small>${SLOTS[base.slot]} · ${equipped?`比較：${esc(ITEMS[equipped.baseId].name)}`:'目前未裝備'} · ${selected.identified?'可直接穿戴':'需要先鑑定'}</small>${compare}</div><button id="equipment-use-selected" class="primary">${selected.identified?'穿戴':'鑑定'}</button>`;}else actions.innerHTML='<span>點一下物品可查看屬性差異；雙擊可快速穿戴。</span>';this.bindItems(grid);const use=actions.querySelector<HTMLButtonElement>('#equipment-use-selected');if(use&&selected)use.onclick=()=>this.game.command({type:selected.identified?'equip':'identify',id:selected.id});
 }
 private positionItemTooltip(anchor:HTMLElement,panel:HTMLElement|null|undefined,width:number){
  const rect=anchor.getBoundingClientRect(),panelRect=panel?.getBoundingClientRect(),headerRect=panel?.querySelector<HTMLElement>('header')?.getBoundingClientRect(),viewport=window.visualViewport,viewLeft=viewport?.offsetLeft??0,viewTop=viewport?.offsetTop??0,viewWidth=viewport?.width??innerWidth,viewHeight=viewport?.height??innerHeight,height=this.tooltip.offsetHeight,gap=10;
  const minLeft=viewLeft+8,maxLeft=Math.max(minLeft,viewLeft+viewWidth-width-8),minTop=viewTop+8,maxTop=Math.max(minTop,viewTop+viewHeight-height-8),clampLeft=(value:number)=>Math.min(maxLeft,Math.max(minLeft,value)),clampTop=(value:number)=>Math.min(maxTop,Math.max(minTop,value));
  const overlapsAnchor=(left:number,top:number)=>left<rect.right+4&&left+width>rect.left-4&&top<rect.bottom+4&&top+height>rect.top-4;
  const isInventory=panel?.classList.contains('panel-inventory')??false,isEquipment=panel?.classList.contains('panel-equipment')??false;
  let left=clampLeft(panelRect?panelRect.left+(panelRect.width-width)/2:rect.left+(rect.width-width)/2),top=clampTop((headerRect?.bottom??panelRect?.top??viewTop)+8);
  if(isInventory&&panelRect){
   const rightSpace=viewLeft+viewWidth-panelRect.right,leftSpace=panelRect.left-viewLeft;
   if(rightSpace>=width+gap)left=panelRect.right+gap;else if(leftSpace>=width+gap)left=panelRect.left-width-gap;else left=rightSpace>=leftSpace?maxLeft:minLeft;
   top=clampTop(Math.min(rect.top,panelRect.bottom-height));
  }else if(isEquipment&&panelRect){
   // Character/equipment tooltips must never cover the item currently under the pointer.
   // Prefer outside the window; when there is not enough desktop space, dock to the opposite
   // side of the character window and only fall back to above/below the hovered slot.
   const rightSpace=viewLeft+viewWidth-panelRect.right,leftSpace=panelRect.left-viewLeft,anchorOnLeft=(rect.left+rect.right)/2<(panelRect.left+panelRect.right)/2;
   if(rightSpace>=width+gap){left=panelRect.right+gap;top=clampTop(rect.top);}
   else if(leftSpace>=width+gap){left=panelRect.left-width-gap;top=clampTop(rect.top);}
   else {left=clampLeft(anchorOnLeft?panelRect.right-width-12:panelRect.left+12);top=clampTop((headerRect?.bottom??panelRect.top)+8);}
   if(overlapsAnchor(left,top)){
    const below=clampTop(rect.bottom+gap),above=clampTop(rect.top-height-gap);
    if(!overlapsAnchor(left,below))top=below;else if(!overlapsAnchor(left,above))top=above;else{left=clampLeft(anchorOnLeft?maxLeft:minLeft);top=clampTop(rect.bottom+gap);}
   }
  }
  this.tooltip.style.left=`${clampLeft(left)}px`;this.tooltip.style.top=`${clampTop(top)}px`;
 }
 private showTooltip(item:ItemInstance,anchor:HTMLElement){const base=ITEMS[item.baseId],stats=itemStats(item),equipped=base.slot?this.snap!.self.equipment[base.slot]:undefined,other=equipped?itemStats(equipped):undefined;
  this.tooltip.innerHTML=`<div class="tooltip-title" style="--rarity:${RARITIES[item.rarity].color}">${icon(base.icon)}<div><h3>${esc(base.name)}${item.enhancementLevel?` +${item.enhancementLevel}`:''}</h3><span>${RARITIES[item.rarity].name} · ${base.slot?SLOTS[base.slot]:'山海靈材'}</span></div></div><div class="tooltip-meta"><span>需求 Lv. ${base.requiredLevel}</span><span>品相 ${item.quality}%</span></div><div class="tooltip-stats">${Object.entries(stats).filter(([,v])=>v!==0).map(([k,v])=>{const diff=other?v-other[k as keyof typeof other]:0;return `<p><span>${STAT_NAMES[k as keyof typeof STAT_NAMES]}</span><b>${v}${PERCENT_STATS.has(k)?'%':''}</b>${other?`<em class="${diff>=0?'up':'down'}">${diff>=0?'▲':'▼'} ${Math.abs(Math.round(diff))}</em>`:''}</p>`;}).join('')}</div>${!item.identified?'<p class="unidentified">器紋尚隱 · 鑑定後顯現隨機詞綴</p>':item.affixes.length?`<div class="affix-list">${item.affixes.map(a=>`<p>✧ ${STAT_NAMES[a.stat]} +${a.value}${PERCENT_STATS.has(a.stat)?'%':''} <small>(${a.min}–${a.max})</small></p>`).join('')}</div>`:''}<p class="item-lore">${esc(base.description)}</p>${base.vfx?`<div class="effect-note">◈ 器靈外觀 · ${base.vfx==='lightning'?'紫電纏刃':base.vfx==='flame'?'焰息流轉':base.vfx==='frost'?'寒霜凝晶':'靈紋流光'}</div>`:''}<div class="tooltip-source">來源：${esc(base.dropSource.join('、')||'行者初裝')}<br>耐久 ${item.durability}/100 · 可交易<br>基準售值 ${base.sellPrice} 靈石 · 強化 ${item.enhancementLevel}/10</div>${equipped&&equipped.id!==item.id?`<div class="compare-label">比較目前裝備：${esc(ITEMS[equipped.baseId].name)}</div>`:''}`;
  this.tooltip.hidden=false;const panel=anchor.closest<HTMLElement>('.game-panel'),isInventory=panel?.classList.contains('panel-inventory')??false,isEquipment=panel?.classList.contains('panel-equipment')??false,viewport=window.visualViewport,viewWidth=viewport?.width??innerWidth,panelWidth=panel?.getBoundingClientRect().width??300,width=Math.min(300,Math.max(210,Math.min(isInventory?300:panelWidth,viewWidth)-16));this.tooltip.style.width=`${width}px`;this.tooltip.classList.toggle('inventory-side-tooltip',isInventory);this.tooltip.classList.toggle('equipment-avoid-tooltip',isEquipment);this.positionItemTooltip(anchor,panel,width);
 }
 openNpc(id:string){this.currentNpc=id;if(!this.panels.has('npc'))this.createPanel('npc','山海見聞','一席清談 · 半卷山海');const npc=NPCS.find(n=>n.id===id)!,body=this.body('npc');body.innerHTML=`<div class="npc-portrait">${icon('person')}<div><h3>${npc.name}</h3><span>${npc.role}</span></div><span class="npc-seal">聞</span></div><p class="npc-dialog">「${npc.dialog}」</p><div class="intel-list">${npc.intel.map(id=>{const m=MONSTERS[id],r=REGIONS.find(r=>r.id===m.spawnArea)!,loot=LOOT_TABLES[m.lootTable].entries.filter(e=>ITEMS[e.itemId].type==='equipment').slice(0,3);return `<article><div><strong>${m.name}</strong><span>Lv. ${m.recommendedLevel}</span></div><p>${r.name} · ${loot.map(e=>ITEMS[e.itemId].name).join('、')}</p><button data-navigate="${m.id}">開始導航 ↗</button><button data-bestiary="${m.id}">查看圖鑑</button></article>`;}).join('')}</div>${id==='smith'?'<button class="primary" id="repair-all">修理全身装備 · 20 靈石</button>':''}${id==='broker'?'<button class="primary" id="npc-market">瀏覽玩家市集</button>':''}`;
  body.querySelectorAll<HTMLButtonElement>('[data-navigate]').forEach(b=>b.onclick=()=>{const m=MONSTERS[b.dataset.navigate!],r=REGIONS.find(r=>r.id===m.spawnArea)!;this.game.command({type:'navigate',x:r.x+(m.spawnOffset?.x??0),z:r.z+(m.spawnOffset?.z??0)+8,label:`${r.name} · ${m.name}`});this.close('npc');});body.querySelectorAll<HTMLButtonElement>('[data-bestiary]').forEach(b=>b.onclick=()=>{this.bestiaryId=b.dataset.bestiary!;if(!this.panels.has('bestiary'))this.toggle('bestiary');else this.renderBestiary();});body.querySelector<HTMLButtonElement>('#repair-all')?.addEventListener('click',()=>this.game.command({type:'repair'}));body.querySelector<HTMLButtonElement>('#npc-market')?.addEventListener('click',()=>this.toggle('market'));
 }
 private renderMap(){const body=this.body('map');body.innerHTML='<div class="world-map"><canvas width="800" height="630"></canvas><div class="map-legend"><span>◆ 異獸棲息地</span><span>◇ 聚落與居民</span><span>所有地區均可自由進入</span></div></div><footer><span>青嵐谷 · 各地實力有別，量力而行</span><small>點選地面開始導航</small></footer>';this.worldMap=body.querySelector('canvas')!;drawMap(this.worldMap,this.snap);this.worldMap.onclick=e=>{const r=this.worldMap!.getBoundingClientRect(),span=WORLD.half*2,x=(e.clientX-r.left)/r.width*span-WORLD.half,z=(e.clientY-r.top)/r.height*span-WORLD.half;this.game.command({type:'navigate',x,z,label:'地圖標記'});this.close('map');};}
 private renderBestiary(){const body=this.body('bestiary'),p=this.snap!.self;this.previews.get('bestiary')?.dispose();this.previews.delete('bestiary');const m=MONSTERS[this.bestiaryId]??Object.values(MONSTERS)[0],known=p.known.includes(m.id),table=LOOT_TABLES[m.lootTable];
  body.innerHTML=`<div class="bestiary-layout"><nav>${Object.values(MONSTERS).map(d=>`<button data-monster="${d.id}" class="${d.id===m.id?'active':''}"><span>${p.known.includes(d.id)?d.name:'未聞異獸'}</span><small>${p.known.includes(d.id)?`Lv. ${d.level} · ${d.element}`:'？？？'}</small></button>`).join('')}</nav><div class="bestiary-detail">${known?`<div class="bestiary-model"></div><div class="bestiary-heading"><h3>${m.name}</h3><span>${m.aiProfile==='boss'?(m.bossTitle??'地圖王'):'山海異獸'} · Lv. ${m.level}</span></div><p>${m.description}</p><div class="bestiary-meta"><span>棲息地 ${REGIONS.find(r=>r.id===m.spawnArea)?.name}</span><span>討伐 ${p.kills[m.id]??0} 次</span></div><h4>可能掉落</h4><div class="loot-list">${table.entries.map(e=>`<span style="color:${RARITIES[ITEMS[e.itemId].rarity].color}">${ITEMS[e.itemId].name}${e.itemId==='kui-drum'?' · 專屬':''}</span>`).join('')}</div>${table.guaranteed?.some(e=>e.conditions==='firstKill')?`<small>初次討伐必得：${table.guaranteed.map(e=>ITEMS[e.itemId].name).join('、')}</small>`:''}<button class="primary" id="bestiary-nav">前往棲息地 ↗</button>`:'<div class="unknown-beast">？<h3>山霧未散</h3><p>向行山客詢問，或親自探索此異獸。</p></div>'}</div></div>`;
  body.querySelectorAll<HTMLButtonElement>('[data-monster]').forEach(b=>b.onclick=()=>{this.bestiaryId=b.dataset.monster!;this.renderBestiary();});if(known){if(this.game.graphics.previews){const preview=new ModelPreview(body.querySelector<HTMLElement>('.bestiary-model')!);preview.setMonster(m);this.previews.set('bestiary',preview);}else body.querySelector<HTMLElement>('.bestiary-model')!.innerHTML='<div class="preview-disabled">3D 預覽已關閉</div>';body.querySelector<HTMLButtonElement>('#bestiary-nav')!.onclick=()=>{const r=REGIONS.find(r=>r.id===m.spawnArea)!;this.game.command({type:'navigate',x:r.x,z:r.z+8,label:m.name});this.close('bestiary');};}
 }
 private marketSignature='';
 private renderMarket(force:boolean){const body=this.body('market'),s=this.snap!;if(!body.querySelector('#market-search')){
   body.innerHTML=`<div class="market-filters"><input id="market-search" placeholder="搜尋裝備名稱或詞綴…"/><select id="market-rarity"><option value="">所有品質</option>${Object.entries(RARITIES).map(([id,r])=>`<option value="${id}">${r.name}</option>`).join('')}</select><select id="market-slot"><option value="">所有部位</option>${Object.entries(SLOTS).map(([id,s])=>`<option value="${id}">${s}</option>`).join('')}</select></div><div id="market-listings"></div><div class="market-sell"><h3>上架行囊中的物品</h3><select id="sell-item"></select><input id="sell-price" type="number" min="1" max="1000000000" value="100" aria-label="靈石售價"/><button class="primary" id="sell-submit">上架</button></div><div class="nearby-players"><h3>附近行者 · 當面交易</h3><div id="trade-players"></div></div>`;
   for(const id of ['market-search','market-rarity','market-slot'])body.querySelector<HTMLInputElement>('#'+id)!.oninput=()=>this.renderMarket(true);
   body.querySelector<HTMLButtonElement>('#sell-submit')!.onclick=()=>this.game.command({type:'list',item:body.querySelector<HTMLSelectElement>('#sell-item')!.value,price:Number(body.querySelector<HTMLInputElement>('#sell-price')!.value)});
  }
  const query=body.querySelector<HTMLInputElement>('#market-search')!.value,rarity=body.querySelector<HTMLSelectElement>('#market-rarity')!.value,slot=body.querySelector<HTMLSelectElement>('#market-slot')!.value,signature=JSON.stringify([s.listings,s.self.revision,s.players.map(p=>p.id)]);if(!force&&signature===this.marketSignature)return;this.marketSignature=signature;
  const listings=s.listings.filter(l=>(!rarity||l.item.rarity===rarity)&&(!slot||ITEMS[l.item.baseId].slot===slot)&&(!query||(ITEMS[l.item.baseId].name+l.item.affixes.map(a=>STAT_NAMES[a.stat]).join('')).includes(query)));
  body.querySelector('#market-listings')!.innerHTML=listings.length?listings.map(l=>`<article class="listing"><div class="listing-icon" style="color:${RARITIES[l.item.rarity].color}">${icon(ITEMS[l.item.baseId].icon)}</div><div><strong style="color:${RARITIES[l.item.rarity].color}">${esc(ITEMS[l.item.baseId].name)}</strong><small>${esc(l.sellerName)} · 品相 ${l.item.quality}% · ${l.item.affixes.map(a=>`${STAT_NAMES[a.stat]}+${a.value}`).join(' / ')}</small></div><b>${l.price} <small>靈石</small></b><button data-listing="${l.id}" data-own="${l.seller===s.self.id}">${l.seller===s.self.id?'取回':'購買'}</button></article>`).join(''):'<div class="market-empty">'+icon('coin')+'<h3>好器待有緣人</h3><p>目前沒有符合條件的玩家委託。<br>把旅途中拾得的靈器，交給下一位行者。</p></div>';
  body.querySelectorAll<HTMLButtonElement>('[data-listing]').forEach(b=>b.onclick=()=>this.game.command({type:b.dataset.own==='true'?'unlist':'buy',id:b.dataset.listing!}));const select=body.querySelector<HTMLSelectElement>('#sell-item')!,old=select.value;select.innerHTML=s.self.inventory.map(i=>`<option value="${i.id}">${esc(ITEMS[i.baseId].name)} · ${i.quality}%</option>`).join('');if(s.self.inventory.some(i=>i.id===old))select.value=old;else if(this.inventorySelection)select.value=this.inventorySelection;
  body.querySelector('#trade-players')!.innerHTML=s.players.filter(p=>p.id!==s.self.id).map(p=>`<button data-player="${p.id}">${esc(p.name)} · Lv. ${p.level} <span>邀請交易</span></button>`).join('')||'<p>尚無其他在線行者。可在另一瀏覽器建立角色加入同一世界。</p>';body.querySelectorAll<HTMLButtonElement>('[data-player]').forEach(b=>b.onclick=()=>this.game.command({type:'tradeRequest',player:b.dataset.player!}));
 }
 private tradeSignature='';
 private renderTrade(){const s=this.snap!,t=s.trade!,signature=JSON.stringify(t);if(signature===this.tradeSignature)return;this.tradeSignature=signature;const body=this.body('trade');body.innerHTML=`<div class="trade-columns">${t.participants.map(id=>{const offer=t.offers[id],own=id===s.self.id,player=s.players.find(p=>p.id===id);return `<div><h3>${esc(player?.name??'行者')} ${offer.locked?'· 已鎖定':''}</h3>${own?`<div class="trade-pick">${s.self.inventory.slice(0,48).map(i=>`<label><input type="checkbox" value="${i.id}" ${offer.items.includes(i.id)?'checked':''}/> ${esc(ITEMS[i.baseId].name)}</label>`).join('')}</div><label>靈石 <input id="trade-gold" type="number" min="0" value="${offer.gold}"/></label>`:`<div class="trade-pick">${offer.items.map(id=>`<p>${esc((t as unknown as {itemDetails?:Record<string,string>}).itemDetails?.[id]??'對方裝備')} <small>${id.slice(0,8)}</small></p>`).join('')||'<p>尚未提出物品</p>'}</div><p>${offer.gold} 靈石</p>`}<small>${offer.confirmed?'已最終確認':offer.locked?'等待雙方最終確認':'檢查交易內容'}</small></div>`;}).join('')}</div><p class="trade-notice">任何物品或金額更動，都會取消雙方鎖定與確認。</p><footer><span>提案版本 ${t.revision}</span><button id="trade-lock">鎖定提案</button><button class="primary" id="trade-confirm" ${Object.values(t.offers).every(o=>o.locked)?'':'disabled'}>最終確認</button></footer>`;
  const update=()=>this.game.command({type:'tradeOffer',items:[...body.querySelectorAll<HTMLInputElement>('input[type=checkbox]:checked')].map(i=>i.value),gold:Number(body.querySelector<HTMLInputElement>('#trade-gold')!.value)});body.querySelectorAll<HTMLInputElement>('input').forEach(i=>i.onchange=update);body.querySelector<HTMLButtonElement>('#trade-lock')!.onclick=()=>this.game.command({type:'tradeLock',revision:t.revision});body.querySelector<HTMLButtonElement>('#trade-confirm')!.onclick=()=>this.game.command({type:'tradeConfirm',revision:t.revision});
 }
 private renderCreator(){
  const body=this.body('creator'),profile=this.game.getCharacterCustomization();
  const avatarId=this.game.getAvatarCandidate();
  const avatarOptions=AVATAR_CANDIDATES.map(a=>`<option value="${a.id}" ${a.id===avatarId?'selected':''}>${a.label}</option>`).join('');
  const rows=(groups:CustomGroup[])=>CUSTOM_CONTROLS.filter(c=>groups.includes(c.group)).map(c=>`<label class="creator-slider"><span>${c.label}<small>${c.hint??''}</small></span><input type="range" min="${c.min??0}" max="${c.max??100}" value="${profile[c.key]}" data-custom-key="${c.key}"/><output>${profile[c.key]}</output></label>`).join('');
  const option=(key:keyof typeof profile,values:string[])=>`<label>${values[0]} <select data-custom-option="${String(key)}">${values.slice(1).map((v,i)=>`<option value="${i}">${v}</option>`).join('')}</select></label>`;
  const faceCards=FACE_PRESETS.map((p,i)=>`<button class="creator-preset ${profile.facePreset===i?'active':''}" data-face-preset="${i}"><b>${p.name}</b><span>${p.description}</span></button>`).join('');
  const bodyCards=BODY_PRESETS.map((p,i)=>`<button class="creator-preset ${profile.bodyPreset===i?'active':''}" data-body-preset="${i}"><b>${p.name}</b><span>${p.description}</span></button>`).join('');
  const avatarCards=AVATAR_CANDIDATES.map(a=>`<button class="creator-preset avatar-choice ${a.id===avatarId?'active':''}" data-avatar-candidate="${a.id}">${a.preview?`<img src="${a.preview}" alt="" loading="lazy"/>`:'<span class="avatar-choice-placeholder">青嵐</span>'}<b>${a.label}</b><span>${a.subtitle}</span></button>`).join('');
  body.innerHTML=`<div class="creator-banner"><div><b>P0.23.8 · MULTI VRM CHARACTER SELECT</b><span>11 個可切換 VRM · 通用 Humanoid Adapter · 獨立裝備層 · RightHand 武器掛點 · 自動 Fallback</span></div><label class="avatar-provider">主角 VRM <select id="creator-avatar-candidate">${avatarOptions}</select></label><label><input id="creator-base-preview" type="checkbox"/> 隱藏目前裝備</label></div>
   <div class="creator-camera"><span>檢視</span><button data-creator-view="face">臉部</button><button data-creator-view="body">上身</button><button data-creator-view="full" class="active">全身</button><i></i><button data-preview-anim="Idle">待機</button><button data-preview-anim="Attack1">攻擊 1</button><button data-preview-anim="Attack2">攻擊 2</button><button data-preview-anim="Attack3">攻擊 3</button><button data-preview-anim="ThunderCast">技能</button></div>
   <nav class="creator-tabs"><button class="active" data-creator-tab="avatar">選角</button><button data-creator-tab="preset">預設</button><button data-creator-tab="face">臉型</button><button data-creator-tab="eyes">眼眉</button><button data-creator-tab="nose">鼻子</button><button data-creator-tab="mouth">嘴耳</button><button data-creator-tab="body">身體</button><button data-creator-tab="style">造型</button></nav>
   <section class="creator-pane active" data-creator-pane="avatar"><h3>VRM 角色選擇</h3><div class="creator-preset-grid">${avatarCards}</div><p><small>選擇後立即保存於本機；切換期間保留目前角色，待新 VRM 通過 Humanoid 驗證後再無縫接手。</small></p></section>
   <section class="creator-pane" data-creator-pane="preset"><h3>臉部預設</h3><div class="creator-preset-grid">${faceCards}</div><h3>身體預設</h3><div class="creator-preset-grid">${bodyCards}</div><div class="creator-save"><b>外觀欄位</b>${[1,2,3,4,5].map(i=>`<span><button data-save-slot="${i}">儲存 ${i}</button><button data-load-slot="${i}">讀取 ${i}</button></span>`).join('')}</div></section>
   <section class="creator-pane" data-creator-pane="face"><h3>臉型細節</h3>${rows(['face'])}</section>
   <section class="creator-pane" data-creator-pane="eyes"><h3>眼睛</h3>${rows(['eyes'])}<h3>眉毛</h3>${rows(['brows'])}</section>
   <section class="creator-pane" data-creator-pane="nose"><h3>鼻子</h3>${rows(['nose'])}</section>
   <section class="creator-pane" data-creator-pane="mouth"><h3>嘴唇</h3>${rows(['mouth'])}<h3>耳朵</h3>${rows(['ears'])}</section>
   <section class="creator-pane" data-creator-pane="body"><h3>體型細節</h3>${rows(['body'])}</section>
   <section class="creator-pane" data-creator-pane="style"><h3>髮型與色彩</h3>${rows(['style'])}<div class="creator-colors">
    <label>膚色 <input type="color" value="${profile.skinColor}" data-custom-color="skinColor"/></label><label>髮色 <input type="color" value="${profile.hairColor}" data-custom-color="hairColor"/></label><label>左眼 <input type="color" value="${profile.leftEyeColor}" data-custom-color="leftEyeColor"/></label><label>右眼 <input type="color" value="${profile.rightEyeColor}" data-custom-color="rightEyeColor"/></label><label>唇色 <input type="color" value="${profile.lipColor}" data-custom-color="lipColor"/></label><label>內衣褲 <input type="color" value="${profile.underwearColor}" data-custom-color="underwearColor"/></label><label>紋身色 <input type="color" value="${profile.tattooColor}" data-custom-color="tattooColor"/></label><label>妝容色 <input type="color" value="${profile.makeupColor}" data-custom-color="makeupColor"/></label>
    ${option('hairStyle',['髮型','長髮束冠','束髮精簡','短髮戰鬥型'])}${option('browStyle',['眉型','自然','平眉','劍眉','挑眉'])}${option('eyelashStyle',['睫毛','無','短','中','長'])}${option('adornmentStyle',['飾點','無','美人痣','額心玉','金環','星砂'])}${option('tattooStyle',['紋身','無','頰紋','額紋','眼紋','月紋'])}${option('makeupStyle',['妝容','無','淡妝','柔妝','濃妝'])}${option('voiceStyle',['聲線','清朗','沉穩','凌厲','低沉'])}
    <button id="creator-voice-preview">聲線預覽</button></div>
    <div class="creator-transfer"><button id="creator-export">匯出外觀 JSON</button><label class="button-like">匯入外觀 JSON<input id="creator-import" type="file" accept="application/json,.json" hidden/></label></div>
   </section>
   <div class="creator-note"><b>角色架構</b><span>P0.23.8 使用通用 VRM Humanoid Adapter；角色選單可直接切換 11 組 VRM，Walk/Run/Pickup/Attack 直接驅動角色自身 Humanoid，武器使用掌心 Grip Socket 對齊並跟隨最終手部骨架。Idle/Walk/Run/Attack/Skill 直接由 Humanoid 動作層驅動；衣袍、鞋、飾品維持獨立裝備層，近戰攻擊包含手腕翻轉與握拳姿勢。VRM 載入或動畫驗證失敗時自動保留緊急角色，不再讓人物消失。</span></div>
   <footer><span>V 開關塑形 · 右鍵旋轉 · 滾輪縮放 · 數值即時保存</span><button id="creator-random">隨機</button><button id="creator-reset">全部重置</button></footer>`;
  this.game.setCharacterCreatorView('full');
  const setSelect=(key:string,value:number)=>{const el=body.querySelector<HTMLSelectElement>(`[data-custom-option="${key}"]`);if(el)el.value=String(value);};
  ['hairStyle','browStyle','eyelashStyle','adornmentStyle','tattooStyle','makeupStyle','voiceStyle'].forEach(k=>setSelect(k,Number(profile[k as keyof typeof profile])));
  body.querySelectorAll<HTMLButtonElement>('[data-creator-tab]').forEach(button=>button.onclick=()=>{const tab=button.dataset.creatorTab!;body.querySelectorAll('[data-creator-tab]').forEach(x=>x.classList.toggle('active',x===button));body.querySelectorAll<HTMLElement>('[data-creator-pane]').forEach(p=>p.classList.toggle('active',p.dataset.creatorPane===tab));if(tab==='face'||tab==='eyes'||tab==='nose'||tab==='mouth')this.game.setCharacterCreatorView('face');else if(tab==='body')this.game.setCharacterCreatorView('body');else this.game.setCharacterCreatorView('full');});
  body.querySelectorAll<HTMLInputElement>('[data-custom-key]').forEach(input=>input.oninput=()=>{const key=input.dataset.customKey as import('../character/customization').NumericCustomizationKey,value=Number(input.value);input.nextElementSibling!.textContent=String(value);this.game.setCharacterCustomizationKey(key,value);});
  body.querySelectorAll<HTMLInputElement>('[data-custom-color]').forEach(input=>input.oninput=()=>this.game.setCharacterStyleColor(input.dataset.customColor as 'skinColor'|'hairColor'|'leftEyeColor'|'rightEyeColor'|'lipColor'|'underwearColor'|'tattooColor'|'makeupColor',input.value));
  body.querySelectorAll<HTMLSelectElement>('[data-custom-option]').forEach(select=>select.onchange=()=>this.game.setCharacterOption(select.dataset.customOption as keyof import('../character/customization').CharacterCustomization,Number(select.value) as never));
  body.querySelectorAll<HTMLButtonElement>('[data-face-preset]').forEach(b=>b.onclick=()=>{this.game.applyCharacterFacePreset(Number(b.dataset.facePreset));this.renderCreator();});
  body.querySelectorAll<HTMLButtonElement>('[data-body-preset]').forEach(b=>b.onclick=()=>{this.game.applyCharacterBodyPreset(Number(b.dataset.bodyPreset));this.renderCreator();});
  body.querySelectorAll<HTMLButtonElement>('[data-save-slot]').forEach(b=>b.onclick=()=>this.toast(this.game.saveCharacterCustomizationSlot(Number(b.dataset.saveSlot))?`外觀已儲存至欄位 ${b.dataset.saveSlot}`:'儲存失敗'));
  body.querySelectorAll<HTMLButtonElement>('[data-load-slot]').forEach(b=>b.onclick=()=>{if(this.game.loadCharacterCustomizationSlot(Number(b.dataset.loadSlot)))this.renderCreator();else this.toast(`欄位 ${b.dataset.loadSlot} 尚未儲存外觀`);});
  body.querySelectorAll<HTMLButtonElement>('[data-creator-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.creatorView as 'face'|'body'|'full';this.game.setCharacterCreatorView(v);body.querySelectorAll('[data-creator-view]').forEach(x=>x.classList.toggle('active',x===b));});
  body.querySelectorAll<HTMLButtonElement>('[data-preview-anim]').forEach(b=>b.onclick=()=>{if(!this.game.previewCharacterAnimation(b.dataset.previewAnim!))this.toast('這個動作尚未載入。');});
  body.querySelector<HTMLSelectElement>('#creator-avatar-candidate')!.onchange=e=>{this.game.setAvatarCandidate((e.target as HTMLSelectElement).value as AvatarCandidateId);this.renderCreator();this.toast('正在切換 VRM；驗證通過後自動接手。');};
  body.querySelectorAll<HTMLButtonElement>('[data-avatar-candidate]').forEach(b=>b.onclick=()=>{this.game.setAvatarCandidate(b.dataset.avatarCandidate as AvatarCandidateId);this.renderCreator();this.toast('已選擇 VRM：'+(b.textContent?.trim()??''));});
  body.querySelector<HTMLInputElement>('#creator-base-preview')!.onchange=e=>this.game.setSelfEquipmentPreview((e.target as HTMLInputElement).checked);
  body.querySelector<HTMLButtonElement>('#creator-voice-preview')!.onclick=()=>this.game.previewCharacterVoice();
  body.querySelector<HTMLButtonElement>('#creator-export')!.onclick=()=>{const blob=new Blob([this.game.exportCharacterCustomization()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='qinglan-character-appearance.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);};
  body.querySelector<HTMLInputElement>('#creator-import')!.onchange=async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;const ok=this.game.importCharacterCustomization(await file.text());if(ok)this.renderCreator();else this.toast('外觀檔案格式不正確。');};
  body.querySelector<HTMLButtonElement>('#creator-random')!.onclick=()=>{this.game.setSelfEquipmentPreview(false);this.game.randomizeCharacterCustomization();this.renderCreator();};
  body.querySelector<HTMLButtonElement>('#creator-reset')!.onclick=()=>{this.game.setSelfEquipmentPreview(false);this.game.resetCharacterCustomization();this.renderCreator();};
 }
 private syncGraphicsSettingsUI(body:HTMLElement){const x=this.game.graphics,preset=body.querySelector<HTMLSelectElement>('#quality-preset'),resolution=body.querySelector<HTMLSelectElement>('#resolution'),dynamicResolution=body.querySelector<HTMLInputElement>('#dynamic-resolution'),shadowQuality=body.querySelector<HTMLSelectElement>('#shadow-quality'),charShadow=body.querySelector<HTMLInputElement>('#character-shadow'),monsterShadow=body.querySelector<HTMLInputElement>('#monster-shadow'),modelDetail=body.querySelector<HTMLSelectElement>('#model-detail'),animationDetail=body.querySelector<HTMLSelectElement>('#animation-detail'),vegetation=body.querySelector<HTMLSelectElement>('#vegetation'),vfx=body.querySelector<HTMLSelectElement>('#vfx'),postProcessing=body.querySelector<HTMLSelectElement>('#post-processing'),labels=body.querySelector<HTMLInputElement>('#labels-toggle'),preview=body.querySelector<HTMLInputElement>('#preview-toggle'),minimap=body.querySelector<HTMLSelectElement>('#minimap-fps'),view=body.querySelector<HTMLSelectElement>('#view-distance');if(preset)preset.value=x.preset;if(resolution)resolution.value=String(x.pixelRatio);if(dynamicResolution)dynamicResolution.checked=x.dynamicResolution;if(shadowQuality)shadowQuality.value=x.shadows?x.shadowQuality:'off';if(charShadow){charShadow.checked=x.characterShadows;charShadow.disabled=!x.shadows;}if(monsterShadow){monsterShadow.checked=x.monsterShadows;monsterShadow.disabled=!x.shadows;}if(modelDetail)modelDetail.value=x.modelDetail;if(animationDetail)animationDetail.value=x.animationDetail;if(vegetation)vegetation.value=x.vegetation;if(vfx)vfx.value=x.vfx;if(postProcessing)postProcessing.value=x.postProcessing;if(labels)labels.checked=x.worldLabels;if(preview)preview.checked=x.previews;if(minimap)minimap.value=String(x.minimapFps);if(view)view.value=x.viewDistance;}
 private refreshGraphicsCapabilityUI(body:HTMLElement){const capability=this.game.getGraphicsCapability(),select=body.querySelector<HTMLSelectElement>('#quality-preset');if(select){for(const option of Array.from(select.options)){if(option.value==='custom')continue;const value=option.value as FixedGraphicsPreset,base=option.dataset.baseLabel??option.textContent??graphicsPresetLabel(value);option.dataset.baseLabel=base;const hardwareBlocked=!presetAllowed(value,capability.hardwareMaxPreset),runtimeBlocked=!presetAllowed(value,capability.maxPreset);option.disabled=runtimeBlocked;option.textContent=base+(hardwareBlocked?'（硬體不足）':runtimeBlocked?'（安全鎖定）':'');}}const diagnostics=this.game.getGraphicsDiagnostics(),set=(selector:string,value:string)=>{const el=body.querySelector<HTMLElement>(selector);if(el)el.textContent=value;};set('#settings-hardware-tier',`${diagnostics.hardwareTier} · 硬體上限 ${graphicsPresetLabel(diagnostics.hardwareMaxPreset)}`);set('#settings-max-quality',`${diagnostics.maxPresetLabel} · ${diagnostics.runtimeReason}`);set('#settings-system-resources',`${diagnostics.cores} 執行緒 · RAM ${diagnostics.memoryGBEstimated?'約 ':''}${diagnostics.memoryGB} GB${diagnostics.memoryGBEstimated?'（瀏覽器未提供實際值）':''} · ${(diagnostics.physicalPixels/1_000_000).toFixed(2)} MP`);set('#settings-gpu-limits',`Texture ${diagnostics.maxTextureSize} · Renderbuffer ${diagnostics.maxRenderbufferSize} · MSAA ${diagnostics.maxSamples}x`);}
 private renderSettings(){
  const body=this.body('settings'),g=this.game.graphics,diagnostics=this.game.getGraphicsDiagnostics();
  const settingsEditorLink=CLOUD_RUNTIME?'':`<a class="editor-link" href="/editor">${icon('settings')} 開啟本地世界工坊 ↗</a>`;
  body.innerHTML=`<nav class="settings-tabs"><button class="active" data-settings-tab="graphics">3D 圖形</button><button data-settings-tab="interface">介面</button><button data-settings-tab="controls">操作</button><button data-settings-tab="system">系統資訊</button></nav>
   <section class="settings-pane active" data-settings-pane="graphics">
    <div class="settings-section"><h3>3D 細節與效能</h3>
     <label class="setting-row emphasis"><span><b>品質預設</b><small>手機會自動限制高耗能全畫面效果與超解析度，保留模型／材質品質</small></span><select id="quality-preset"><option value="verylow">極低 · 舊內顯</option><option value="low">效能優先</option><option value="balanced">平衡美術</option><option value="high">電影級</option><option value="custom">自訂</option></select></label>
     <label class="setting-row"><span>3D 模型細節<small>控制遠處人物、怪物的顯示距離</small></span><select id="model-detail"><option value="low">低 · 近距離</option><option value="balanced">中 · 標準</option><option value="high">高 · 最遠</option></select></label>
     <label class="setting-row"><span>遠距動畫細節<small>遠處角色降低動畫更新率可減少 CPU 負擔</small></span><select id="animation-detail"><option value="low">低</option><option value="balanced">中</option><option value="high">高</option></select></label>
     <label class="setting-row"><span>渲染解析度<small>對 GPU 負擔影響最大之一；低配建議 0.70–0.85×</small></span><select id="resolution"><option value="0.7">極低 · 0.70×</option><option value="0.85">效能 · 0.85×</option><option value="1">原生 · 1.00×</option><option value="1.25">精細 · 1.25×</option><option value="1.5">超精細 · 1.50×</option></select></label>
     <label class="setting-row emphasis"><span>動態解析度<small>偵測持續掉幀時逐級降 Render Scale，穩定後再緩慢恢復</small></span><input id="dynamic-resolution" type="checkbox"/></label>
     <label class="setting-row"><span>動態陰影品質<small>可完全關閉；高品質使用 2048 陰影貼圖</small></span><select id="shadow-quality"><option value="off">關閉</option><option value="low">低 · 512</option><option value="medium">中 · 1024</option><option value="high">高 · 2048</option></select></label>
     <label class="setting-row sub-setting"><span>人物陰影<small>僅影響角色 Shadow Proxy</small></span><input id="character-shadow" type="checkbox"/></label>
     <label class="setting-row sub-setting"><span>怪物陰影<small>僅影響異獸 Shadow Proxy</small></span><input id="monster-shadow" type="checkbox"/></label>
     <label class="setting-row"><span>植被細節<small>草地是最主要的植被實例數量來源</small></span><select id="vegetation"><option value="off">關閉</option><option value="low">精簡 · 無草叢</option><option value="full">完整</option></select></label>
     <label class="setting-row"><span>戰鬥與掉寶特效<small>控制粒子、掉寶光柱等 VFX</small></span><select id="vfx"><option value="off">關閉</option><option value="reduced">精簡</option><option value="full">完整</option></select></label>
     <label class="setting-row emphasis"><span>仙俠電影渲染<small>電影級啟用 AO、Bloom、冷青陰影／暖珊瑚高光、微銳化、顆粒與空氣透視；輕量模式保留核心調色</small></span><select id="post-processing"><option value="off">效能優先</option><option value="light">仙俠輕量</option><option value="cinematic">AI 修仙短劇感</option></select></label>
     <label class="setting-row"><span>遠景距離<small>影響霧距與世界區塊載入範圍</small></span><select id="view-distance"><option value="near">近</option><option value="balanced">標準</option><option value="far">遠</option></select></label>
    </div>
    <div class="graphics-hint"><b>硬體畫質鎖定</b><span>目前最高允許：${esc(diagnostics.maxPresetLabel)}。GPU、CPU、RAM、螢幕像素與 Render Target 能力會共同限制預設與自訂畫質；超限選項不可繞過。</span></div>
   </section>
   <section class="settings-pane" data-settings-pane="interface">
    <div class="settings-section"><h3>介面與額外 3D 預覽</h3>
     <label class="setting-row"><span>世界名稱／怪物血條<small>關閉後停止世界標籤 DOM 投影運算</small></span><input id="labels-toggle" type="checkbox"/></label>
     <label class="setting-row"><span>裝備／圖鑑 3D 預覽<small>關閉可停止額外的預覽 WebGL Renderer</small></span><input id="preview-toggle" type="checkbox"/></label>
     <label class="setting-row"><span>小地圖更新率<small>降低更新率可減少 Canvas 重畫</small></span><select id="minimap-fps"><option value="2">低 · 2 FPS</option><option value="5">中 · 5 FPS</option><option value="10">高 · 10 FPS</option></select></label>
     <label class="setting-row"><span>遊戲音效</span><input id="audio-toggle" type="checkbox" ${this.game.audio.enabled?'checked':''}/></label>
    </div>
   </section>
   <section class="settings-pane" data-settings-pane="controls">
    <div class="controls-help"><h3>行旅操作</h3><p><b>手機：</b>左側虛擬搖桿移動；往上推為前進、往下拉為後退，推至外圈自動奔跑。右半畫面拖曳旋轉視角；右側攻擊與技能鍵戰鬥。</p><p><b>桌機：</b>WASD 移動 · Shift 奔跑 · Space 跳躍 · <b>G 御劍／落地</b></p><p>左鍵地面 尋路 · 左鍵異獸 選取 · 雙擊攻擊</p><p>右鍵拖曳 視角 · 滾輪 縮放 · Tab 切換目標</p><p>1–4 武器技能 · 5 踏雲 · 6 補給 · 7 傳說武器專屬技能</p><p><b>V</b> 開啟塑形 · <b>F10</b> 3D 圖形設定</p></div>${settingsEditorLink}
   </section>
   <section class="settings-pane" data-settings-pane="system">
    <div class="settings-section system-diagnostics"><h3>系統資訊與測試診斷</h3>
     <div class="diagnostic-row"><span>版本／架構</span><b>${esc(BUILD_DISPLAY)}</b></div>
     <div class="diagnostic-row"><span>連線狀態</span><b id="settings-connection-status">${esc(this.connectionStatus)}</b></div>
     <div class="diagnostic-row"><span>地圖狀態</span><b id="settings-map-status">${esc(this.mapStatus)}</b></div>
     <div class="diagnostic-row"><span>硬體分級</span><b id="settings-hardware-tier">${esc(diagnostics.hardwareTier)} · 硬體上限 ${esc(graphicsPresetLabel(diagnostics.hardwareMaxPreset))}</b></div>
     <div class="diagnostic-row"><span>最高允許畫質</span><b id="settings-max-quality">${esc(diagnostics.maxPresetLabel)} · ${esc(diagnostics.runtimeReason)}</b></div>
     <div class="diagnostic-row"><span>CPU / RAM / 像素</span><b id="settings-system-resources">${diagnostics.cores} 執行緒 · RAM ${diagnostics.memoryGB} GB · ${(diagnostics.physicalPixels/1_000_000).toFixed(2)} MP</b></div>
     <div class="diagnostic-row"><span>GPU</span><b>${esc(diagnostics.gpu)}</b></div>
     <div class="diagnostic-row"><span>WebGL 能力</span><b id="settings-gpu-limits">Texture ${diagnostics.maxTextureSize} · Renderbuffer ${diagnostics.maxRenderbufferSize} · MSAA ${diagnostics.maxSamples}x</b></div>
     <div class="diagnostic-row"><span>實際渲染保護</span><b>${diagnostics.maxRenderTargetDimension}px Render Target · 後處理 ${diagnostics.postProcessing}</b></div>
     <div class="diagnostic-row"><span>執行模式</span><b>${CLOUD_RUNTIME?'Cloudflare Pages / Durable World':'本機開發 / Local World'}</b></div>
     <p class="diagnostic-note">版本、場景、碰撞與部署診斷只在此處顯示，不再覆蓋遊戲畫面。</p>
     <div class="character-session-actions">
      <button id="return-character-select" type="button">返回角色選擇</button>
      <small>目前角色進度保存在伺服器；返回後可登入此裝置已保存的其他角色，或建立名稱不重複的新角色。</small>
     </div>
    </div>
   </section>
   <div class="settings-live"><span>即時效能</span><strong class="performance-info">—</strong></div>`;
  const preset=body.querySelector<HTMLSelectElement>('#quality-preset')!,resolution=body.querySelector<HTMLSelectElement>('#resolution')!,dynamicResolution=body.querySelector<HTMLInputElement>('#dynamic-resolution')!,shadowQuality=body.querySelector<HTMLSelectElement>('#shadow-quality')!,charShadow=body.querySelector<HTMLInputElement>('#character-shadow')!,monsterShadow=body.querySelector<HTMLInputElement>('#monster-shadow')!,modelDetail=body.querySelector<HTMLSelectElement>('#model-detail')!,animationDetail=body.querySelector<HTMLSelectElement>('#animation-detail')!,vegetation=body.querySelector<HTMLSelectElement>('#vegetation')!,vfx=body.querySelector<HTMLSelectElement>('#vfx')!,postProcessing=body.querySelector<HTMLSelectElement>('#post-processing')!,labels=body.querySelector<HTMLInputElement>('#labels-toggle')!,preview=body.querySelector<HTMLInputElement>('#preview-toggle')!,minimap=body.querySelector<HTMLSelectElement>('#minimap-fps')!,view=body.querySelector<HTMLSelectElement>('#view-distance')!;
  const sync=()=>this.syncGraphicsSettingsUI(body);sync();this.refreshGraphicsCapabilityUI(body);
  body.querySelectorAll<HTMLButtonElement>('[data-settings-tab]').forEach(button=>button.onclick=()=>{const tab=button.dataset.settingsTab!;body.querySelectorAll('[data-settings-tab]').forEach(x=>x.classList.toggle('active',x===button));body.querySelectorAll<HTMLElement>('[data-settings-pane]').forEach(p=>p.classList.toggle('active',p.dataset.settingsPane===tab));});
  preset.onchange=()=>{if(preset.value!=='custom')this.game.setGraphicsPreset(preset.value as 'verylow'|'low'|'balanced'|'high');sync();};
  resolution.onchange=()=>{this.game.setGraphicsSetting('pixelRatio',Number(resolution.value) as .7|.85|1|1.25|1.5);sync();};dynamicResolution.onchange=()=>{this.game.setGraphicsSetting('dynamicResolution',dynamicResolution.checked);sync();};
  shadowQuality.onchange=()=>{const value=shadowQuality.value;if(value==='off')this.game.setGraphicsSetting('shadows',false);else{this.game.setGraphicsSetting('shadowQuality',value as 'low'|'medium'|'high');this.game.setGraphicsSetting('shadows',true);}sync();};
  charShadow.onchange=()=>this.game.setGraphicsSetting('characterShadows',charShadow.checked);monsterShadow.onchange=()=>this.game.setGraphicsSetting('monsterShadows',monsterShadow.checked);
  modelDetail.onchange=()=>this.game.setGraphicsSetting('modelDetail',modelDetail.value as 'low'|'balanced'|'high');animationDetail.onchange=()=>this.game.setGraphicsSetting('animationDetail',animationDetail.value as 'low'|'balanced'|'high');
  vegetation.onchange=()=>this.game.setGraphicsSetting('vegetation',vegetation.value as 'off'|'low'|'full');vfx.onchange=()=>this.game.setGraphicsSetting('vfx',vfx.value as 'off'|'reduced'|'full');postProcessing.onchange=()=>this.game.setGraphicsSetting('postProcessing',postProcessing.value as 'off'|'light'|'cinematic');labels.onchange=()=>this.game.setGraphicsSetting('worldLabels',labels.checked);preview.onchange=()=>this.game.setGraphicsSetting('previews',preview.checked);minimap.onchange=()=>this.game.setGraphicsSetting('minimapFps',Number(minimap.value) as 2|5|10);view.onchange=()=>this.game.setGraphicsSetting('viewDistance',view.value as 'near'|'balanced'|'far');body.querySelector<HTMLInputElement>('#audio-toggle')!.onchange=e=>this.game.audio.setEnabled((e.target as HTMLInputElement).checked);
  body.querySelector<HTMLButtonElement>('#return-character-select')!.onclick=()=>{clearActiveLocalCharacter();location.reload();};
 }
 onGraphicsChanged(){if(!this.game.graphics.previews){for(const p of this.previews.values())p.dispose();this.previews.clear();}if(this.snap&&this.panels.has('equipment'))this.renderEquipment();if(this.snap&&this.panels.has('bestiary'))this.renderBestiary();if(this.panels.has('settings')){const body=this.body('settings');this.syncGraphicsSettingsUI(body);this.refreshGraphicsCapabilityUI(body);}}
 frame(dt:number,time:number){
  const flight=this.root.querySelector<HTMLElement>('#flight-status');if(flight)flight.hidden=!this.snap?.self.flight;
  if(performance.now()>this.toastUntil)this.root.querySelector('#toast')!.classList.remove('visible');
  if(this.snap){this.root.querySelectorAll<HTMLButtonElement>('[data-skill]').forEach(b=>{const skill=b.dataset.skill!,until=this.snap!.self.cooldowns[skill]??0,remaining=Math.max(0,until-time),span=b.querySelector<HTMLElement>('.cooldown')!;span.textContent=remaining>.05?remaining.toFixed(remaining<1?1:0):'';b.classList.toggle('on-cooldown',remaining>.05);});}
  for(const d of this.damageLabels){d.age+=dt;const p=this.game.project(d.event.x!,heightAt(d.event.x!,d.event.z!)+1.7+d.age*.8,d.event.z!);d.el.style.transform=`translate(${p.x}px,${p.y}px) translate(-50%,-50%)`;d.el.style.opacity=String(Math.max(0,1-d.age/.95));if(d.age>1)d.el.remove();}this.damageLabels=this.damageLabels.filter(d=>d.age<1);
  this.previewFrame+=dt;if(this.previewFrame>1/24){for(const preview of this.previews.values())preview.update(this.previewFrame,time);this.previewFrame=0;}
  const metrics=this.panels.get('settings')?.querySelector('.performance-info');if(metrics)metrics.textContent=`${this.game.fps} FPS · ${this.game.runtimeRenderScale.toFixed(2)}× · ${this.game.world.loadedChunks} 區塊 · ${this.game.renderer.info.render.calls} draw calls`;
 }
}
import { heightAt } from '../../shared/data/world';
