/** AUTO-GENERATED by the HF9 local editor import pipeline. Do not hand edit. */
import type {Appearance,ItemBase} from '../types';
export const EDITOR_IMPORTED_ITEMS:Readonly<Record<string,ItemBase>>={};
export const EDITOR_IMPORTED_APPEARANCES:Readonly<Record<string,Appearance>>={};
