import { Color3,Mesh,MeshBuilder,PBRMaterial,Scene,StandardMaterial,TransformNode,Vector3 } from '@babylonjs/core';
import type { Actor,Drop,GameEvent,Monster } from '../../shared/types';
import { heightAt } from '../../shared/data/world';
import { RARITIES } from '../../shared/data/rarities';
import { MONSTERS } from '../../shared/data/monsters';
import { SKILL_DEFINITIONS } from '../../shared/data/skills';

type VfxQuality='off'|'reduced'|'full';
type Burst={mesh:Mesh;life:number;max:number;velocity:Vector3};
type Telegraph={root:TransformNode;started:number;hitAt:number;materials:StandardMaterial[]};

function alphaMat(scene:Scene,name:string,color:string,alpha:number,additive=false){const m=new StandardMaterial(name,scene);m.diffuseColor=Color3.FromHexString(color);m.emissiveColor=m.diffuseColor.scale(additive?.75:.18);m.alpha=alpha;m.backFaceCulling=false;m.disableLighting=additive;m.needDepthPrePass=false;return m;}

export class VisualEffects{
  readonly drops=new Map<string,TransformNode>();
  private bursts:Burst[]=[];private telegraphs=new Map<string,Telegraph>();private quality:VfxQuality='full';private age=0;
  constructor(private scene:Scene){}
  setQuality(q:VfxQuality){this.quality=q;for(const d of this.drops.values())d.setEnabled(q!=='off'||true);for(const t of this.telegraphs.values())t.root.setEnabled(q!=='off');}
  burst(x:number,y:number,z:number,color:string,count=18,strength=2){if(this.quality==='off')return;const n=this.quality==='reduced'?Math.max(2,Math.ceil(count*.3)):Math.min(count,36);for(let i=0;i<n;i++){const m=MeshBuilder.CreateSphere('QL-VfxMote',{diameter:.055+Math.random()*.06,segments:4},this.scene),mat=new PBRMaterial('QL-VfxMoteMat',this.scene);mat.albedoColor=Color3.FromHexString(color);mat.emissiveColor=mat.albedoColor;mat.emissiveIntensity=2.1;mat.roughness=.4;m.material=mat;m.position.set(x,y,z);m.isPickable=false;const a=Math.random()*Math.PI*2,s=.4+Math.random()*strength;this.bursts.push({mesh:m,life:.35+Math.random()*.55,max:1,velocity:new Vector3(Math.cos(a)*s,.7+Math.random()*strength,Math.sin(a)*s)});}}
  event(e:GameEvent,_serverTime?:number){if(e.x===undefined||e.z===undefined)return;const y=heightAt(e.x,e.z)+.9,element=SKILL_DEFINITIONS[e.skill??'']?.element,color=element==='lightning'?'#C7A8FF':element==='fire'?'#FF9563':element==='frost'?'#B8E9F2':element==='wind'?'#A7D9CE':'#E3D0A0';if(e.type==='hit')this.burst(e.x,y,e.z,e.critical?'#FFD49A':color,e.critical?30:16,2.2);if(e.type==='drop'||e.type==='pickup')this.burst(e.x,y-.4,e.z,RARITIES[e.rarity??'common']?.color??'#D8E0D9',24,1.25);}
  private createDrop(d:Drop){const root=new TransformNode(`Drop-${d.id}`,this.scene);root.position.set(d.x,heightAt(d.x,d.z)+.12,d.z);root.metadata={dropId:d.id};const rarity=RARITIES[d.item.rarity];const crystal=MeshBuilder.CreatePolyhedron('QL-DropCrystal',{type:1,size:.26},this.scene);const mat=new PBRMaterial('QL-DropMat',this.scene);mat.albedoColor=Color3.FromHexString(rarity?.color??'#D6E0D9');mat.emissiveColor=mat.albedoColor.scale(.42);mat.emissiveIntensity=.9;mat.roughness=.28;mat.metallic=.18;crystal.material=mat;crystal.position.y=.28;crystal.parent=root;crystal.metadata={dropId:d.id};const ring=MeshBuilder.CreateTorus('QL-DropRing',{diameter:.72,thickness:.035,tessellation:24},this.scene);ring.rotation.x=Math.PI/2;ring.material=alphaMat(this.scene,'QL-DropRingMat',rarity?.color??'#D6E0D9',.65,true);ring.parent=root;ring.metadata={dropId:d.id};return root;}
  private createTelegraph(m:Monster){const a=m.attack!,def=MONSTERS[m.defId],skill=SKILL_DEFINITIONS[a.skill],radius=Math.max(.8,skill?.radius??def?.combatRadius??1.2);const root=new TransformNode(`Telegraph-${m.id}-${a.id}`,this.scene);root.position.set(a.point.x,heightAt(a.point.x,a.point.z)+.045,a.point.z);const materials:StandardMaterial[]=[];for(const [scale,alpha] of [[1,.12],[.98,.68]] as const){const disc=scale===1?MeshBuilder.CreateDisc('QL-TelegraphFill',{radius,tessellation:48},this.scene):MeshBuilder.CreateTorus('QL-TelegraphBorder',{diameter:radius*2,thickness:.045,tessellation:48},this.scene);disc.rotation.x=Math.PI/2;const material=alphaMat(this.scene,'QL-TelegraphMat','#D97866',alpha,true);disc.material=material;disc.parent=root;materials.push(material);}return {root,started:a.started,hitAt:a.hitAt,materials};}
  sync(drops:Drop[],monsters:Monster[],_self?:Actor){const ids=new Set(drops.map(d=>d.id));for(const [id,g] of this.drops)if(!ids.has(id)){g.dispose(false,true);this.drops.delete(id);}for(const d of drops){let g=this.drops.get(d.id);if(!g){g=this.createDrop(d);this.drops.set(d.id,g);}g.position.x=d.x;g.position.z=d.z;g.position.y=heightAt(d.x,d.z)+.12;}
    const active=new Set<string>();for(const m of monsters)if(m.attack&&!m.attack.resolved&&m.hp>0){const key=`${m.id}:${m.attack.id}`;active.add(key);if(!this.telegraphs.has(key)){const t=this.createTelegraph(m);t.root.setEnabled(this.quality!=='off');this.telegraphs.set(key,t);}}for(const [key,t] of this.telegraphs)if(!active.has(key)){t.root.dispose(false,true);this.telegraphs.delete(key);}}
  update(dt:number,time:number){for(const g of this.drops.values()){g.rotation.y+=dt*.72;g.position.y+=Math.sin(time*2.2+g.uniqueId)*.0015;}for(let i=this.bursts.length-1;i>=0;i--){const b=this.bursts[i];b.life-=dt;if(b.life<=0){b.mesh.dispose(false,true);this.bursts.splice(i,1);continue;}b.velocity.y-=2.1*dt;b.mesh.position.addInPlace(b.velocity.scale(dt));b.mesh.scaling.setAll(Math.max(.05,b.life/b.max));}for(const t of this.telegraphs.values()){const f=Math.max(0,Math.min(1,(time-t.started)/Math.max(.001,t.hitAt-t.started)));t.materials[0].alpha=.08+f*.26;t.materials[1].alpha=.44+f*.5;t.root.rotation.y+=dt*.08;}this.age+=dt;}
  dispose(){for(const g of this.drops.values())g.dispose(false,true);for(const t of this.telegraphs.values())t.root.dispose(false,true);for(const b of this.bursts)b.mesh.dispose(false,true);this.drops.clear();this.telegraphs.clear();this.bursts=[];}
}
